package ai.whylabs.core.enums;

public enum TargetTable {
  PROFILE_SEGMENTED,
  PROFILE_OVERALL,
  PROFILE_REFERENCE_PROFILE,
  PROFILE_UNMERGED,
  PROFILE_AUDIT,
  ANALYZER_RESULTS,
  ANALYZER_RUNS,
  MONITOR_CONFIG
}
