export const AppRoutePaths = {
  login: 'login',
  root: '/',
  rootIndex: undefined,
  orgId: ':orgId',
  orgIdIndex: undefined,
  orgIdResourcesSummary: 'resources',
  orgIdDashboards: 'dashboards',
  orgIdDashboardsIndex: undefined,
  orgIdDashboardsWidgetId: ':widgetId',
  create: 'create',
  newWidget: 'new-widget',
  orgIdDashboardId: ':dashboardId',
  orgIdDashboardIdIndex: undefined,
  orgIdPlayground: 'playground',
  orgIdPlaygroundIndex: undefined,
  orgIdResourceId: ':resourceId',
  orgIdResourceIdIndex: undefined,
  orgIdSettings: 'settings',
  orgIdSettingsIndex: undefined,
  orgIdSettingsAccessToken: 'access-tokens',
  orgIdSettingsBilling: 'billing',
  orgIdSettingsIntegrations: 'integrations',
  orgIdSettingsResourceManagement: 'resource-management',
  orgIdSettingsNotificationsIndex: undefined,
  orgIdSettingsNotifications: 'notifications',
  orgIdSettingsNotificationDetails: ':notificationActionId',
  orgIdSettingsUserManagement: 'user-management',
  orgIdSettingsUserManagementEdit: ':userId',
  resourceIdSingleProfile: 'single-profile',
  resourceIdConstraints: 'constraints',
  resourceIdSegmentAnalysis: 'segment-analysis',
  resourceIdLlmTrace: 'llm-secure',
  resourceIdLlmTraceIndex: undefined,
  resourceIdLlmTraceSummary: 'summary',
  resourceIdLlmTracePolicy: 'policy',
  resourceIdLlmTracePolicyIndex: undefined,
  resourceIdLlmTracePolicyAdvancedSettings: 'advanced-settings',
  resourceIdLlmTracePolicyChangeHistory: 'change-history',
  resourceIdLlmTraceTab: 'traces',
  traceId: ':traceId',
  traceIdItemId: ':itemId',
  resourceIdLlmTracesEmbeddingsProjector: 'embeddings-projector',

  // Deprecated paths, used for redirect
  deprecatedLlmTrace: 'llm-trace',
  deprecatedLlmTraceIncludingAllChildren: 'llm-trace/*',
} as const;

export type AppRoutePathIds = keyof typeof AppRoutePaths;
