type LocalIntegrationType = {
  coming_soon: boolean;
  description: string;
  title: string;
  logo: string;
  url: string;
  category: string;
};

export const LocalIntegrations: LocalIntegrationType[] = [
  {
    coming_soon: false,
    description:
      'Switch on WhyLabs observability in a few clicks in the AWS Marketplace. We are AWS experts, so bring your toughest ML monitoring challenges over.',
    logo: 'https://integrations-images.s3.us-west-2.amazonaws.com/awsLogo.webp',
    title: 'AWS',
    url: 'https://docs.whylabs.ai/docs/integrations-cloud/#aws',
    category: 'clouds',
  },
  {
    coming_soon: false,
    description:
      'Big data pipelines, distributed data pipelines, AutoML pipelines, Databricks model serving... all of these can be monitored today.',
    logo: 'https://integrations-images.s3.us-west-2.amazonaws.com/databrickslogo.svg',
    title: 'Databricks',
    url: 'https://docs.whylabs.ai/docs/integrations-databricks/',
    category: 'clouds',
  },
  {
    coming_soon: false,
    description: 'If you call Azure your home, switching on WhyLabs is as easy as adding three lines of code.',
    logo: 'https://integrations-images.s3.us-west-2.amazonaws.com/azureLogo.svg',
    title: 'Azure',
    url: 'https://docs.whylabs.ai/docs/integrations-cloud/#microsoft-azure',
    category: 'clouds',
  },
  {
    coming_soon: false,
    description: 'WhyLabs can monitor your hybrid & multi-cloud data and ML solutions hosted on GCP.',
    logo: 'https://integrations-images.s3.us-west-2.amazonaws.com/cloudLogo.webp',
    title: 'Google Cloud',
    url: 'https://docs.whylabs.ai/docs/integrations-cloud/#google-cloud-platform-gcp',
    category: 'clouds',
  },
  {
    coming_soon: false,
    description: 'Monitor and log data in motion so your organization can innovate in the digital-first world.',
    logo: 'https://integrations-images.s3.us-west-2.amazonaws.com/confluentLogo.png',
    title: 'Confluent',
    url: 'https://whylabs.ai/blog/posts/data-quality-monitoring-for-kafka-beyond-schema-validation',
    category: 'clouds',
  },
  {
    coming_soon: false,
    description: 'Power up observability and monitoring for your AI applications running on Snowflake!',
    logo: 'https://integrations-images.s3.us-west-2.amazonaws.com/SnowflakeLogo.webp',
    title: 'Snowflake',
    url: 'https://docs.whylabs.ai/docs/integrations-snowflake/',
    category: 'clouds',
  },
  {
    coming_soon: false,
    description:
      'Plug whylogs open source telemetry agent to your custom infrastructure. For containerized architecture, use our container as a sidecar. We’ve got you covered!',
    logo: 'https://integrations-images.s3.us-west-2.amazonaws.com/LogoPlaceholder.svg',
    title: 'On Premise',
    url: 'https://docs.whylabs.ai/docs/integrations-cloud/#on-premises',
    category: 'clouds',
  },
  {
    coming_soon: false,
    description: 'From GPT-3 to GPT-100, we cover them all.',
    logo: 'https://integrations-images.s3.us-west-2.amazonaws.com/openaiLogo.webp',
    title: 'OpenAI',
    url: 'https://docs.whylabs.ai/docs/integration-openai/',
    category: 'generative-ai',
  },
  {
    coming_soon: false,
    description: 'Support for every flavor of Claude.',
    logo: 'https://integrations-images.s3.us-west-2.amazonaws.com/anthropicLogo.webp',
    title: 'Anthropic',
    url: 'https://docs.whylabs.ai/docs/secure/integ-bedrock/',
    category: 'generative-ai',
  },
  {
    coming_soon: false,
    description: 'Chains, agents, tools, and more. We have you covered.',
    logo: 'https://integrations-images.s3.us-west-2.amazonaws.com/LangChainLogo.webp',
    title: 'LangChain',
    url: 'https://github.com/langchain-ai/langchain/blob/master/docs/integrations/whylabs_profiling.ipynb',
    category: 'generative-ai',
  },
  {
    coming_soon: false,
    description: 'Distributed big data? We are not afraid of scale!',
    logo: 'https://integrations-images.s3.us-west-2.amazonaws.com/ApacheSparkLogo.svg',
    title: 'Apache Spark',
    url: 'https://docs.whylabs.ai/docs/spark-integration/',
    category: 'data-sources',
  },
  {
    coming_soon: false,
    description: 'Streamed data is streaming data bug - let’s monitor it!',
    logo: 'https://integrations-images.s3.us-west-2.amazonaws.com/kafkaLogo.svg',
    title: 'Apache Kafka',
    url: 'https://docs.whylabs.ai/docs/kafka-integration/',
    category: 'data-sources',
  },
  {
    coming_soon: false,
    description: 'Distributed applications get distributed monitoring...',
    logo: 'https://integrations-images.s3.us-west-2.amazonaws.com/RayLogo.svg',
    title: 'Ray',
    url: 'https://docs.whylabs.ai/docs/ray-integration/',
    category: 'data-sources',
  },
  {
    coming_soon: false,
    description: 'Data driven since 1979. We make sure this data is high quality!',
    logo: 'https://integrations-images.s3.us-west-2.amazonaws.com/TeradataLogo.svg',
    title: 'Teradata',
    url: 'https://whylabs.ai/contact-us',
    category: 'data-sources',
  },
  {
    coming_soon: false,
    description: 'Works with Pandas dataframe out of the box!',
    logo: 'https://integrations-images.s3.us-west-2.amazonaws.com/pandasLogo.svg',
    title: 'Python Pandas',
    url: 'https://github.com/whylabs/whylogs/blob/mainline/python/examples/basic/Getting_Started.ipynb',
    category: 'data-sources',
  },
  {
    coming_soon: false,
    description: 'Python apps of crazy scale should be monitored too, we are on it.',
    logo: 'https://integrations-images.s3.us-west-2.amazonaws.com/daskLogo.webp',
    title: 'Dask',
    url: 'https://whylogs.readthedocs.io/en/latest/examples/integrations/Dask_Profiling.html',
    category: 'data-sources',
  },
  {
    coming_soon: false,
    description: 'No time to freeze with massive scale monitoring on Snowflake!',
    logo: 'https://integrations-images.s3.us-west-2.amazonaws.com/SnowflakeLogo.webp',
    title: 'Snowflake',
    url: 'https://docs.whylabs.ai/docs/integrations-snowflake/',
    category: 'data-sources',
  },
  {
    coming_soon: false,
    description:
      'Include monitoring in your production-grade orchestration for machine learning workflows and data processing.',
    logo: 'https://integrations-images.s3.us-west-2.amazonaws.com/flyteLogo.webp',
    title: 'Flyte / Union AI',
    url: 'https://docs.flyte.org/en/latest/flytesnacks/examples/whylogs_plugin/index.html',
    category: 'data-and-ml-pipelines',
  },
  {
    coming_soon: false,
    description:
      'Open-source data logging meets the open-source MLOps framework for creating portable, production-ready pipelines.',
    logo: 'https://integrations-images.s3.us-west-2.amazonaws.com/zenmlLogo.webp',
    title: 'ZenML',
    url: 'https://docs.zenml.io/stack-components/data-validators/whylogs',
    category: 'data-and-ml-pipelines',
  },
  {
    coming_soon: false,
    description: 'Use whylogs with your Airflow plug-and-play operators to execute your ML monitoring tasks.',
    logo: 'https://integrations-images.s3.us-west-2.amazonaws.com/airflowLogo.webp',
    title: 'Airflow',
    url: 'https://whylabs.ai/blog/posts/data-quality-monitoring-in-apache-airflow-with-whylogs',
    category: 'data-and-ml-pipelines',
  },
  {
    coming_soon: false,
    description: 'MLOps platform built to work with AWS infrastructure now with fully integrated WhyLabs monitoring!',
    logo: 'https://integrations-images.s3.us-west-2.amazonaws.com/amazonSagemakerLogo.svg',
    title: 'Amazon SageMaker',
    url: 'https://aws.amazon.com/blogs/startups/preventing-amazon-sagemaker-model-degradation-with-whylabs/',
    category: 'deployment-managers',
  },
  {
    coming_soon: false,
    description: 'Streamed data is streaming data bug - let’s monitor it!',
    logo: 'https://integrations-images.s3.us-west-2.amazonaws.com/ubiopsLogo.svg',
    title: 'UbiOps',
    url: 'https://whylabs.ai/blog/posts/ubiops-whylabs',
    category: 'deployment-managers',
  },
  {
    coming_soon: false,
    description: 'MLOps platform focused on automation gets automatic monitoring.',
    logo: 'https://integrations-images.s3.us-west-2.amazonaws.com/valohaiLogo.svg',
    title: 'Valohai',
    url: 'https://whylabs.ai/blog/posts/observability-in-production-monitoring-data-drift-with-whylabs-and-valohai',
    category: 'deployment-managers',
  },
  {
    coming_soon: false,
    description: 'High performance, low code ML meets high performance, low code monitoring.',
    logo: 'https://integrations-images.s3.us-west-2.amazonaws.com/PredibaseLogo.svg',
    title: 'Predibase',
    url: 'https://whylabs.ai/contact-us',
    category: 'deployment-managers',
  },
  {
    coming_soon: false,
    description: 'Self-serve monitoring for self-serve deployment with zero MLOps platform',
    logo: 'https://integrations-images.s3.us-west-2.amazonaws.com/TeachableHubLogo.svg',
    title: 'TeachableHub',
    url: 'https://whylabs.ai/blog/posts/deploying-and-monitoring-made-easy-with-teachablehub-and-whylabs',
    category: 'deployment-managers',
  },
  {
    coming_soon: false,
    description: 'If you build, deploy, and scale machine learning models on Vertex, you can monitor them too!',
    logo: 'https://integrations-images.s3.us-west-2.amazonaws.com/VertextAILogo.webp',
    title: 'Vertex AI',
    url: 'https://whylabs.ai/contact-us',
    category: 'deployment-managers',
  },
  {
    coming_soon: false,
    description: 'Monitor your machine learning solutions built Azure ML for even more confidence.',
    logo: 'https://integrations-images.s3.us-west-2.amazonaws.com/azureLogo.svg',
    title: 'Azure ML',
    url: 'https://whylabs.ai/contact-us',
    category: 'deployment-managers',
  },
  {
    coming_soon: false,
    description: 'Automate and monitor your production ML data pipelines with Feast and WhyLabs.',
    logo: 'https://integrations-images.s3.us-west-2.amazonaws.com/feastLogo.webp',
    title: 'Feast',
    url: 'https://whylogs.readthedocs.io/en/latest/examples/integrations/Feature_Stores_and_whylogs.html',
    category: 'feature-stores',
  },
  {
    coming_soon: false,
    description: 'Feature platform for real-time machine learning meets platform for real-time monitoring.',
    logo: 'https://integrations-images.s3.us-west-2.amazonaws.com/tectonLogo.png',
    title: 'Tecton',
    url: 'https://whylabs.ai/contact-us',
    category: 'feature-stores',
  },
  {
    coming_soon: false,
    description: 'We’ll provide the monitoring while Featureform provides the feature store.',
    logo: 'https://integrations-images.s3.us-west-2.amazonaws.com/featureFormLogo.png',
    title: 'FeatureForm',
    url: 'https://whylabs.ai/contact-us',
    category: 'feature-stores',
  },
  {
    coming_soon: false,
    description: 'Data labeling meets data monitoring!',
    logo: 'https://integrations-images.s3.us-west-2.amazonaws.com/SuperbLogo.svg',
    title: 'Superb AI',
    url: 'https://whylabs.ai/blog/posts/data-labeling-meets-data-monitoring-with-superb-ai-and-whylabs',
    category: 'data-labeling-platforms',
  },
  {
    coming_soon: false,
    description:
      'Crowd-sourced data collection and annotation can integrate with ML monitoring in WhyLabs to fix issues such as data drift.',
    logo: 'https://integrations-images.s3.us-west-2.amazonaws.com/tolokaLogo.webp',
    title: 'Toloka',
    url: 'https://whylabs.ai/contact-us',
    category: 'data-labeling-platforms',
  },
  {
    coming_soon: false,
    description: 'The open-source experiment tracker has a deployment tool!',
    logo: 'https://integrations-images.s3.us-west-2.amazonaws.com/MLflowLogo.svg',
    title: 'MLflow',
    url: 'https://whylabs.ai/blog/posts/on-model-lifecycle-and-monitoring',
    category: 'experiment-trackers',
  },
  {
    coming_soon: false,
    description: 'Monitoring for your cutting-edge distributed serving',
    logo: 'https://integrations-images.s3.us-west-2.amazonaws.com/anyscaleLogo.svg',
    title: 'Ray Serve / Anyscale',
    url: 'https://www.anyscale.com/blog/running-and-monitoring-distributed-ml-with-ray-and-whylogs',
    category: 'serving-architectures',
  },
  {
    coming_soon: false,
    description: 'The lightest-weight serving architecture that we know of!',
    logo: 'https://integrations-images.s3.us-west-2.amazonaws.com/bentomlLogo.svg',
    title: 'BentoML',
    url: 'https://github.com/whylabs/whylogs/tree/mainline/python/examples/integrations/bentoml',
    category: 'serving-architectures',
  },
  {
    coming_soon: false,
    description: 'Now you can monitor your models deployed as RESTful API endpoints',
    logo: 'https://integrations-images.s3.us-west-2.amazonaws.com/FastAPILogo.svg',
    title: 'FastAPI',
    url: 'https://github.com/whylabs/whylogs/tree/mainline/python/examples/integrations/fastapi',
    category: 'serving-architectures',
  },
  {
    coming_soon: false,
    description: 'Models deployed as web services need monitoring too',
    logo: 'https://integrations-images.s3.us-west-2.amazonaws.com/FlaskLogo.svg',
    title: 'Flask',
    url: 'https://whylabs.ai/blog/posts/deploy-and-monitor-your-ml-application-with-flask-and-whylabs',
    category: 'serving-architectures',
  },
  {
    coming_soon: false,
    description: 'Get notifications pushed to your team’s favorite chat app',
    logo: 'https://integrations-images.s3.us-west-2.amazonaws.com/slackLogo.webp',
    title: 'Slack',
    url: 'https://docs.whylabs.ai/docs/whylabs-notifications/#slack-notifications',
    category: 'notifications',
  },
  {
    coming_soon: false,
    description: 'Receive email notifications whenever an alert gets created',
    logo: 'https://integrations-images.s3.us-west-2.amazonaws.com/emailLogo.svg',
    title: 'Email',
    url: 'https://docs.whylabs.ai/docs/whylabs-notifications/#email-notifications',
    category: 'notifications',
  },
  {
    coming_soon: false,
    description: 'Get notifications for critical-path MLOps incident response',
    logo: 'https://integrations-images.s3.us-west-2.amazonaws.com/pagerdutyLogo.svg',
    title: 'PagerDuty',
    url: 'https://docs.whylabs.ai/docs/whylabs-notifications/#pagerduty-notifications',
    category: 'notifications',
  },
];
