package ai.whylabs.dataservice.requests;

import ai.whylabs.dataservice.enums.AsyncAnalysisQueue;
import com.fasterxml.jackson.annotation.JsonPropertyDescription;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Data;
import lombok.experimental.FieldNameConstants;
import org.joda.time.Interval;

@FieldNameConstants
@Data
public class AsyncAdhocRequest {
  @JsonPropertyDescription("Required, orgId")
  @Schema(required = true)
  private String orgId;

  @JsonPropertyDescription("Required, datasetId")
  @Schema(required = true)
  private String datasetId;

  private String analyzers;

  /**
   * By default adhoc sinks to a separate table that's ephemeral in nature. This option will sink
   * data to the main tables making the results of the request permanent as if it was generated by
   * the batch monitor flow.
   */
  private boolean promoteResults = false;

  @JsonPropertyDescription(
      "Required, return anomalies within this ISO-8601 time period,\ninclusive of start and exclusive of end point.\ne.g. \"2022-07-01T00:00:00.000Z/P30D\" or \"2022-07-01T00:00:00.000Z/2022-07-01T00:00:00.000Z\"")
  @Schema(required = true, type = "string")
  private Interval interval; //  ISO 8601 formatted interval

  private AsyncAnalysisQueue queue = AsyncAnalysisQueue.on_demand;
}
