package ai.whylabs.dataservice.requests;

import ai.whylabs.dataservice.enums.SortOrder;
import ai.whylabs.dataservice.util.ValidateRequest;
import com.fasterxml.jackson.annotation.JsonPropertyDescription;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.List;
import lombok.Data;
import lombok.experimental.FieldNameConstants;
import org.joda.time.Interval;

@FieldNameConstants
@Data
public class GetAnalyzerRunsRequest {
  @JsonPropertyDescription("Required, orgId")
  @Schema(required = true)
  private String orgId;

  @JsonPropertyDescription("Required, datasetIds")
  @Schema(required = true)
  private List<String> datasetIds;

  @JsonPropertyDescription("Optional, filter by analyzerIds")
  private List<String> analyzerIds;

  @JsonPropertyDescription("Optional, filter by monitorIds")
  private List<String> monitorIds;

  @JsonPropertyDescription(
      "Required, return anomalies within this ISO-8601 time period,\ninclusive of start and exclusive of end point.\ne.g. \"2022-07-01T00:00:00.000Z/P30D\" or \"2022-07-01T00:00:00.000Z/2022-07-01T00:00:00.000Z\"")
  @Schema(required = true, type = "string")
  private Interval interval; //  ISO 8601 formatted interval

  @JsonPropertyDescription("Limit as per sql definition, max " + ValidateRequest.MAX_PAGE_SIZE)
  private Integer limit = 50;

  @JsonPropertyDescription("Offset as per sql definition, max 10")
  private Integer offset = 0;

  @JsonPropertyDescription("Order, (desc, asc). Default desc")
  private SortOrder order = SortOrder.desc;

  @JsonPropertyDescription("Read analysis generated by the PG backed monitors")
  private boolean readPgMonitor = false;
}
