package ai.whylabs.dataservice.requests;

import ai.whylabs.dataservice.enums.DataGranularity;
import ai.whylabs.dataservice.enums.GranularityInclusion;
import ai.whylabs.dataservice.enums.ParentChildScope;
import com.fasterxml.jackson.annotation.JsonPropertyDescription;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.List;
import javax.persistence.ElementCollection;
import lombok.Data;
import lombok.ToString;
import lombok.experimental.FieldNameConstants;
import org.joda.time.Interval;

@FieldNameConstants
@Data
@ToString
public class GetAnomalyCountsRequest {
  @Schema(required = true)
  private String orgId;

  @JsonPropertyDescription("Required, datasetIds")
  @ElementCollection
  @Schema(required = true)
  private List<String> datasetIds;

  @ElementCollection private List<String> analyzerIds;

  @Schema(required = true)
  private DataGranularity granularity;

  @JsonPropertyDescription(
      "Analysis can't be rolled up, so one generally wants to look at either analysis at the bucket level or the individual level")
  @Schema(required = false)
  private GranularityInclusion granularityInclusion = GranularityInclusion.BOTH;

  @JsonPropertyDescription(
      "Optional filter to query for just parent analyzers, just child analyzers, or both")
  @Schema(required = false)
  private ParentChildScope parentChildScope = ParentChildScope.BOTH;

  @JsonPropertyDescription("Filter by monitor ids")
  @ElementCollection
  private List<String> monitorIds;

  @ElementCollection private List<String> segments;
  @ElementCollection private List<String> excludeSegments;

  @ElementCollection private List<String> runIds;

  @ElementCollection private List<String> columnNames;

  @JsonPropertyDescription(
      "Required, return anomalies within this ISO-8601 time period,\ninclusive of start and exclusive of end point.\ne.g. \"2022-07-01T00:00:00.000Z/P30D\" or \"2022-07-01T00:00:00.000Z/2022-07-01T00:00:00.000Z\"")
  @Schema(required = true, type = "string")
  private Interval interval; //  ISO 8601 formatted interval

  @JsonPropertyDescription("Query adhoc generated results (stored separately)")
  private Boolean adhoc = false;

  @JsonPropertyDescription(
      "Analysis can be marked as unhelpful. Flag to indicate whether or not to include unhelpful anomalies in the counts")
  private Boolean includeUnhelpful = false;

  @JsonPropertyDescription("Read analysis generated by the PG backed monitors")
  private boolean readPgMonitor = false;
}
