package ai.whylabs.dataservice.requests;

import ai.whylabs.dataservice.enums.GranularityInclusion;
import ai.whylabs.dataservice.enums.ParentChildScope;
import ai.whylabs.dataservice.enums.SortOrder;
import ai.whylabs.dataservice.util.ValidateRequest;
import com.fasterxml.jackson.annotation.JsonPropertyDescription;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.List;
import lombok.Data;
import lombok.experimental.FieldNameConstants;
import org.joda.time.Interval;

@FieldNameConstants
@Data
public class GetAnalyzerResultRequest {
  @JsonPropertyDescription("Required, orgId")
  @Schema(required = true)
  private String orgId;

  @JsonPropertyDescription("Required, datasetIds")
  @Schema(required = true)
  private List<String> datasetIds;

  @JsonPropertyDescription("Metrics (optional)")
  private List<String> metrics;

  @JsonPropertyDescription("List of column names to search for")
  private List<String> columnNames;

  @JsonPropertyDescription("List of segments to search for")
  private List<String> segments;

  @JsonPropertyDescription("Filter by monitor ids (optional)")
  private List<String> monitorIds;

  @JsonPropertyDescription("Filter out failed analysis")
  private Boolean includeFailures = false;

  @JsonPropertyDescription(
      "Analysis can be marked as unhelpful. Flag to indicate whether or not to include unhelpful analysis")
  private Boolean includeUnhelpful = true;

  @JsonPropertyDescription("Filter to only include results with anomalies")
  private Boolean onlyAnomalies = false;

  @JsonPropertyDescription(
      "Analysis can't be rolled up, so one generally wants to look at either analysis at the bucket level or the individual level")
  @Schema(required = false)
  private GranularityInclusion granularityInclusion = GranularityInclusion.BOTH;

  @JsonPropertyDescription(
      "Optional filter to query for just parent analyzers, just child analyzers, or both")
  @Schema(required = false)
  private ParentChildScope parentChildScope = ParentChildScope.BOTH;

  @JsonPropertyDescription("Query adhoc generated results (stored separately)")
  private Boolean adhoc = false;

  @JsonPropertyDescription("Order, (desc, asc). Default desc")
  private SortOrder order = SortOrder.desc;

  @JsonPropertyDescription("Types of analyzers to return")
  private List<String> analyzerTypes;

  @JsonPropertyDescription("Analyzer ids filter (optional)")
  private List<String> analyzerIds;

  @JsonPropertyDescription("Analysis ids filter (optional)")
  private List<String> analysisIds;

  @JsonPropertyDescription("Run ids filter (optional)")
  private List<String> runIds;

  @JsonPropertyDescription(
      "Required, return anomalies within this ISO-8601 time period,\ninclusive of start and exclusive of end point.\ne.g. \"2022-07-01T00:00:00.000Z/P30D\" or \"2022-07-01T00:00:00.000Z/2022-07-01T00:00:00.000Z\"")
  @Schema(required = true, type = "string")
  private Interval interval; //  ISO 8601 formatted interval

  @JsonPropertyDescription("Limit as per sql definition, max " + ValidateRequest.MAX_PAGE_SIZE)
  private Integer limit = 50;

  @JsonPropertyDescription("Offset as per sql definition, max 10")
  private Integer offset = 0;

  @JsonPropertyDescription("Read analysis generated by the PG backed monitors")
  private boolean readPgMonitor = false;
}
