package ai.whylabs.batch;

import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.closeTo;
import static org.testng.AssertJUnit.assertEquals;

import ai.whylabs.core.configV3.structure.enums.Classifier;
import ai.whylabs.core.configV3.structure.enums.DataType;
import ai.whylabs.core.configV3.structure.enums.DiscretenessType;
import ai.whylabs.core.serde.MonitorConfigV3JsonSerde;
import lombok.val;
import org.testng.annotations.Test;

public class EntitySchemaTest {

  @Test
  public void testParse() {
    String json =
        "{\n"
            + "  \"id\": \"demo-document\",\n"
            + "  \"orgId\": \"org-11\",\n"
            + "  \"schemaVersion\": 1,\n"
            + "  \"datasetId\": \"model-0\",\n"
            + "  \"granularity\": \"daily\",\n"
            + "  \"entitySchema\": {\n"
            + "    \"columns\": {\n"
            + "      \"annual_inc\": {\n"
            + "        \"discreteness\": \"discrete\",\n"
            + "        \"classifier\": \"input\",\n"
            + "        \"dataType\": \"fractional\"\n"
            + "      },\n"
            + "      \"a\": {\n"
            + "        \"discreteness\": \"discrete\",\n"
            + "        \"classifier\": \"input\",\n"
            + "        \"dataType\": \"null\"\n"
            + "      },\n"
            + "      \"b\": {\n"
            + "        \"discreteness\": \"discrete\",\n"
            + "        \"classifier\": \"input\",\n"
            + "        \"dataType\": \"boolean\"\n"
            + "      },\n"
            + "      \"c\": {\n"
            + "        \"discreteness\": \"discrete\",\n"
            + "        \"classifier\": \"input\",\n"
            + "        \"dataType\": \"string\"\n"
            + "      },\n"
            + "      \"d\": {\n"
            + "        \"discreteness\": \"discrete\",\n"
            + "        \"classifier\": \"input\",\n"
            + "        \"dataType\": \"unknown\"\n"
            + "      },\n"
            + "      \"prediction\": {\n"
            + "        \"discreteness\": \"discrete\",\n"
            + "        \"classifier\": \"output\",\n"
            + "        \"dataType\": \"integral\"\n"
            + "      }\n"
            + "    }\n"
            + "  },\n"
            + "  \"analyzers\": [\n"
            + "    {\n"
            + "      \"id\": \"missing_upload_analyzer\",\n"
            + "      \"schedule\": {\n"
            + "        \"type\": \"cron\",\n"
            + "        \"cron\": \"0 * * * *\",\n"
            + "        \"exclusionRanges\": []\n"
            + "      },\n"
            + "      \"disabled\": false,\n"
            + "      \"targetMatrix\": {\n"
            + "        \"type\": \"dataset\",\n"
            + "        \"segments\": [\n"
            + "          {\n"
            + "            \"tags\": []\n"
            + "          },\n"
            + "          {\n"
            + "            \"tags\": [\n"
            + "              {\n"
            + "                \"key\": \"purpose\",\n"
            + "                \"value\": \"small_business\"\n"
            + "              }\n"
            + "            ]\n"
            + "          }\n"
            + "        ],\n"
            + "        \"level\": \"dataset\"\n"
            + "      },\n"
            + "      \"config\": {\n"
            + "        \"type\": \"fixed\",\n"
            + "        \"version\": 1,\n"
            + "        \"metric\": \"secondsSinceLastUpload\",\n"
            + "        \"upper\": 86400000,\n"
            + "        \"lower\": 0,\n"
            + "        \"analyzerType\": \"fixed\"\n"
            + "      }\n"
            + "    },\n"
            + "    {\n"
            + "      \"id\": \"missing_datapoint_analyzer\",\n"
            + "      \"schedule\": {\n"
            + "        \"type\": \"cron\",\n"
            + "        \"cron\": \"0 * * * *\",\n"
            + "        \"exclusionRanges\": []\n"
            + "      },\n"
            + "      \"disabled\": false,\n"
            + "      \"targetMatrix\": {\n"
            + "        \"type\": \"dataset\",\n"
            + "        \"segments\": [\n"
            + "          {\n"
            + "            \"tags\": []\n"
            + "          },\n"
            + "          {\n"
            + "            \"tags\": [\n"
            + "              {\n"
            + "                \"key\": \"purpose\",\n"
            + "                \"value\": \"small_business\"\n"
            + "              }\n"
            + "            ]\n"
            + "          }\n"
            + "        ],\n"
            + "        \"level\": \"dataset\"\n"
            + "      },\n"
            + "      \"dataReadinessDuration\": 14400,\n"
            + "      \"config\": {\n"
            + "        \"type\": \"fixed\",\n"
            + "        \"version\": 1,\n"
            + "        \"metric\": \"missingDatapoint\",\n"
            + "        \"upper\": 0,\n"
            + "        \"analyzerType\": \"fixed\"\n"
            + "      }\n"
            + "    },\n"
            + "    {\n"
            + "      \"id\": \"drift_analyzer\",\n"
            + "      \"schedule\": {\n"
            + "        \"type\": \"cron\",\n"
            + "        \"cron\": \"0 * * * *\",\n"
            + "        \"exclusionRanges\": []\n"
            + "      },\n"
            + "      \"disabled\": false,\n"
            + "      \"targetMatrix\": {\n"
            + "        \"type\": \"column\",\n"
            + "        \"segments\": [\n"
            + "          {\n"
            + "            \"tags\": []\n"
            + "          },\n"
            + "          {\n"
            + "            \"tags\": [\n"
            + "              {\n"
            + "                \"key\": \"purpose\",\n"
            + "                \"value\": \"small_business\"\n"
            + "              }\n"
            + "            ]\n"
            + "          }\n"
            + "        ],\n"
            + "        \"include\": [\n"
            + "          \"*\"\n"
            + "        ]\n"
            + "      },\n"
            + "      \"config\": {\n"
            + "        \"type\": \"stddev\",\n"
            + "        \"version\": 1,\n"
            + "        \"metric\": \"median\",\n"
            + "        \"params\": {},\n"
            + "        \"maxUpperThreshold\": \"Infinity\",\n"
            + "        \"minLowerThreshold\": \"-Infinity\",\n"
            + "        \"factor\": 5,\n"
            + "        \"minBatchSize\": 7,\n"
            + "        \"analyzerType\": \"stddev\",\n"
            + "        \"maxUpper\": \"Infinity\",\n"
            + "        \"minLower\": \"-Infinity\",\n"
            + "        \"baseline\": {\n"
            + "          \"type\": \"TrailingWindow\",\n"
            + "          \"size\": 14\n"
            + "        }\n"
            + "      }\n"
            + "    }\n"
            + "  ],\n"
            + "  \"monitors\": [\n"
            + "    {\n"
            + "      \"id\": \"drift-monitor-1\",\n"
            + "      \"analyzerIds\": [\n"
            + "        \"drift_analyzer\"\n"
            + "      ],\n"
            + "      \"schedule\": {\n"
            + "        \"type\": \"cron\",\n"
            + "        \"cron\": \"0 0 * * * *\",\n"
            + "        \"exclusionRanges\": []\n"
            + "      },\n"
            + "      \"disabled\": false,\n"
            + "      \"severity\": 2,\n"
            + "      \"mode\": {\n"
            + "        \"type\": \"EVERY_ANOMALY\"\n"
            + "      },\n"
            + "      \"actions\": [\n"
            + "        {\n"
            + "          \"type\": \"email\",\n"
            + "          \"target\": \"demo@whylabs.ai\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"type\": \"slack\",\n"
            + "          \"target\": \"https://demo.com\"\n"
            + "        }\n"
            + "      ]\n"
            + "    },\n"
            + "    {\n"
            + "      \"id\": \"drift-monitor-2\",\n"
            + "      \"analyzerIds\": [\n"
            + "        \"drift_analyzer\"\n"
            + "      ],\n"
            + "      \"schedule\": {\n"
            + "        \"type\": \"cron\",\n"
            + "        \"cron\": \"0 0 * * * *\",\n"
            + "        \"exclusionRanges\": []\n"
            + "      },\n"
            + "      \"disabled\": false,\n"
            + "      \"severity\": 2,\n"
            + "      \"mode\": {\n"
            + "        \"type\": \"DIGEST\"\n"
            + "      },\n"
            + "      \"actions\": [\n"
            + "        {\n"
            + "          \"type\": \"email\",\n"
            + "          \"target\": \"demo@whylabs.ai\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"type\": \"slack\",\n"
            + "          \"target\": \"https://demo.com\"\n"
            + "        }\n"
            + "      ]\n"
            + "    }\n"
            + "  ]\n"
            + "}";

    // System.out.println(json);
    val conf = MonitorConfigV3JsonSerde.parseMonitorConfigV3(json);
    val col1 = conf.getEntitySchema().getColumns().get("annual_inc");
    assertEquals(Classifier.input, col1.getClassifier());
    assertEquals(DataType.FRACTIONAL, col1.getDataType());
    assertEquals(DiscretenessType.discrete, col1.getDiscreteness());

    assertEquals(6, conf.getEntitySchema().getColumns().size());

    /**
     * // Create a row that's the opposite of whats in entity schema val row = new
     * QueryResultStructure(Ex .discrete(false) .inferredType(
     * InferredTypePostAggregatorResultStructure.builder().type(Type.BOOLEAN).build()) .build();
     *
     * <p>// Assert that entity schema took preference val schema =
     * MonitorConfigV3Utils.getSchemaWithInferredBackup(conf, "annual_inc", row, null);
     * Assert.assertEquals(DiscretenessType.discrete, schema.getDiscreteness());
     * Assert.assertEquals(Classifier.input, schema.getClassifier());
     */
  }

  @Test
  public void testFeatureImportanceParse() {
    String json =
        "{\n"
            + "  \"id\": \"e463721d-91a6-476d-8529-d2843c293e06\",\n"
            + "  \"schemaVersion\": 1,\n"
            + "  \"orgId\": \"org-0\",\n"
            + "  \"datasetId\": \"model-0\",\n"
            + "  \"granularity\": \"daily\",\n"
            + "  \"metadata\": {\n"
            + "    \"schemaVersion\": 1,\n"
            + "    \"author\": \"d5b189739da0925fd1e3bff96971786b\",\n"
            + "    \"updatedTimestamp\": 1663028619637,\n"
            + "    \"version\": 228\n"
            + "  },\n"
            + "  \"analyzers\": [\n"
            + "    {\n"
            + "      \"id\": \"continuous-distribution-d705bfd0\",\n"
            + "      \"schedule\": {\n"
            + "        \"type\": \"fixed\",\n"
            + "        \"cadence\": \"daily\"\n"
            + "      },\n"
            + "      \"disabled\": false,\n"
            + "      \"targetMatrix\": {\n"
            + "        \"type\": \"column\",\n"
            + "        \"include\": [\n"
            + "          \"group:continuous\"\n"
            + "        ]\n"
            + "      },\n"
            + "      \"backfillGracePeriodDuration\": \"P30D\",\n"
            + "      \"config\": {\n"
            + "        \"metric\": \"histogram\",\n"
            + "        \"type\": \"drift\",\n"
            + "        \"algorithm\": \"hellinger\",\n"
            + "        \"threshold\": 0.7,\n"
            + "        \"minBatchSize\": 1,\n"
            + "        \"baseline\": {\n"
            + "          \"type\": \"TrailingWindow\",\n"
            + "          \"size\": 7\n"
            + "        }\n"
            + "      }\n"
            + "    },\n"
            + "    {\n"
            + "      \"id\": \"discrete-distribution-3ce15ae6\",\n"
            + "      \"schedule\": {\n"
            + "        \"type\": \"fixed\",\n"
            + "        \"cadence\": \"daily\"\n"
            + "      },\n"
            + "      \"disabled\": false,\n"
            + "      \"targetMatrix\": {\n"
            + "        \"type\": \"column\",\n"
            + "        \"include\": [\n"
            + "          \"group:discrete\"\n"
            + "        ]\n"
            + "      },\n"
            + "      \"backfillGracePeriodDuration\": \"P30D\",\n"
            + "      \"config\": {\n"
            + "        \"metric\": \"frequent_items\",\n"
            + "        \"type\": \"drift\",\n"
            + "        \"algorithm\": \"hellinger\",\n"
            + "        \"threshold\": 0.7,\n"
            + "        \"minBatchSize\": 1,\n"
            + "        \"baseline\": {\n"
            + "          \"type\": \"TrailingWindow\",\n"
            + "          \"size\": 7\n"
            + "        }\n"
            + "      }\n"
            + "    },\n"
            + "    {\n"
            + "      \"id\": \"missing-values-ratio-6ae15922\",\n"
            + "      \"schedule\": {\n"
            + "        \"type\": \"fixed\",\n"
            + "        \"cadence\": \"daily\"\n"
            + "      },\n"
            + "      \"disabled\": false,\n"
            + "      \"targetMatrix\": {\n"
            + "        \"type\": \"column\",\n"
            + "        \"include\": [\n"
            + "          \"*\"\n"
            + "        ]\n"
            + "      },\n"
            + "      \"backfillGracePeriodDuration\": \"P30D\",\n"
            + "      \"config\": {\n"
            + "        \"metric\": \"count_null_ratio\",\n"
            + "        \"type\": \"stddev\",\n"
            + "        \"factor\": 3,\n"
            + "        \"minBatchSize\": 1,\n"
            + "        \"baseline\": {\n"
            + "          \"type\": \"TrailingWindow\",\n"
            + "          \"size\": 7\n"
            + "        }\n"
            + "      }\n"
            + "    },\n"
            + "    {\n"
            + "      \"id\": \"unique-ratio-29f3ef1c\",\n"
            + "      \"schedule\": {\n"
            + "        \"type\": \"fixed\",\n"
            + "        \"cadence\": \"daily\"\n"
            + "      },\n"
            + "      \"disabled\": false,\n"
            + "      \"targetMatrix\": {\n"
            + "        \"type\": \"column\",\n"
            + "        \"include\": [\n"
            + "          \"*\"\n"
            + "        ]\n"
            + "      },\n"
            + "      \"backfillGracePeriodDuration\": \"P30D\",\n"
            + "      \"config\": {\n"
            + "        \"metric\": \"unique_est_ratio\",\n"
            + "        \"type\": \"stddev\",\n"
            + "        \"factor\": 3,\n"
            + "        \"minBatchSize\": 1,\n"
            + "        \"baseline\": {\n"
            + "          \"type\": \"TrailingWindow\",\n"
            + "          \"size\": 7\n"
            + "        }\n"
            + "      }\n"
            + "    },\n"
            + "    {\n"
            + "      \"id\": \"missing-profile-analyzer\",\n"
            + "      \"schedule\": {\n"
            + "        \"type\": \"fixed\",\n"
            + "        \"cadence\": \"daily\"\n"
            + "      },\n"
            + "      \"disabled\": false,\n"
            + "      \"targetMatrix\": {\n"
            + "        \"type\": \"dataset\"\n"
            + "      },\n"
            + "      \"backfillGracePeriodDuration\": \"P365D\",\n"
            + "      \"config\": {\n"
            + "        \"metric\": \"secondsSinceLastUpload\",\n"
            + "        \"type\": \"fixed\",\n"
            + "        \"upper\": 86400\n"
            + "      }\n"
            + "    },\n"
            + "    {\n"
            + "      \"id\": \"inferred-data-type-33ee413a\",\n"
            + "      \"schedule\": {\n"
            + "        \"type\": \"fixed\",\n"
            + "        \"cadence\": \"daily\"\n"
            + "      },\n"
            + "      \"targetMatrix\": {\n"
            + "        \"type\": \"column\",\n"
            + "        \"include\": [\n"
            + "          \"group:discrete\"\n"
            + "        ],\n"
            + "        \"exclude\": [\n"
            + "          \"group:output\"\n"
            + "        ],\n"
            + "        \"segments\": []\n"
            + "      },\n"
            + "      \"config\": {\n"
            + "        \"metric\": \"inferred_data_type\",\n"
            + "        \"baseline\": {\n"
            + "          \"type\": \"TrailingWindow\",\n"
            + "          \"size\": 7\n"
            + "        },\n"
            + "        \"type\": \"comparison\",\n"
            + "        \"operator\": \"eq\"\n"
            + "      },\n"
            + "      \"metadata\": {\n"
            + "        \"schemaVersion\": 1,\n"
            + "        \"author\": \"system\",\n"
            + "        \"updatedTimestamp\": 1662584945253,\n"
            + "        \"version\": 1\n"
            + "      }\n"
            + "    },\n"
            + "    {\n"
            + "      \"id\": \"old-tan-loris-9807-analyzer\",\n"
            + "      \"schedule\": {\n"
            + "        \"type\": \"fixed\",\n"
            + "        \"cadence\": \"daily\"\n"
            + "      },\n"
            + "      \"targetMatrix\": {\n"
            + "        \"type\": \"column\",\n"
            + "        \"include\": [\n"
            + "          \"group:discrete\"\n"
            + "        ],\n"
            + "        \"exclude\": [\n"
            + "          \"group:output\"\n"
            + "        ],\n"
            + "        \"segments\": []\n"
            + "      },\n"
            + "      \"config\": {\n"
            + "        \"metric\": \"frequent_items\",\n"
            + "        \"baseline\": {\n"
            + "          \"type\": \"TrailingWindow\",\n"
            + "          \"size\": 7\n"
            + "        },\n"
            + "        \"type\": \"drift\",\n"
            + "        \"algorithm\": \"hellinger\",\n"
            + "        \"threshold\": 0.7\n"
            + "      },\n"
            + "      \"metadata\": {\n"
            + "        \"schemaVersion\": 1,\n"
            + "        \"author\": \"system\",\n"
            + "        \"updatedTimestamp\": 1662675399215,\n"
            + "        \"version\": 1\n"
            + "      }\n"
            + "    }\n"
            + "  ],\n"
            + "  \"monitors\": [\n"
            + "    {\n"
            + "      \"id\": \"continuous-distribution-d705bfd0-monitor\",\n"
            + "      \"analyzerIds\": [\n"
            + "        \"continuous-distribution-d705bfd0\"\n"
            + "      ],\n"
            + "      \"schedule\": {\n"
            + "        \"type\": \"immediate\"\n"
            + "      },\n"
            + "      \"severity\": 3,\n"
            + "      \"mode\": {\n"
            + "        \"type\": \"DIGEST\",\n"
            + "        \"creationTimeOffset\": \"PT2H\",\n"
            + "        \"datasetTimestampOffset\": \"PT26H\"\n"
            + "      },\n"
            + "      \"actions\": []\n"
            + "    },\n"
            + "    {\n"
            + "      \"id\": \"discrete-distribution-3ce15ae6-monitor\",\n"
            + "      \"analyzerIds\": [\n"
            + "        \"discrete-distribution-3ce15ae6\"\n"
            + "      ],\n"
            + "      \"schedule\": {\n"
            + "        \"type\": \"immediate\"\n"
            + "      },\n"
            + "      \"severity\": 3,\n"
            + "      \"mode\": {\n"
            + "        \"type\": \"DIGEST\",\n"
            + "        \"creationTimeOffset\": \"PT2H\",\n"
            + "        \"datasetTimestampOffset\": \"PT26H\"\n"
            + "      },\n"
            + "      \"actions\": []\n"
            + "    },\n"
            + "    {\n"
            + "      \"id\": \"missing-values-ratio-6ae15922-monitor\",\n"
            + "      \"analyzerIds\": [\n"
            + "        \"missing-values-ratio-6ae15922\"\n"
            + "      ],\n"
            + "      \"schedule\": {\n"
            + "        \"type\": \"immediate\"\n"
            + "      },\n"
            + "      \"severity\": 3,\n"
            + "      \"mode\": {\n"
            + "        \"type\": \"DIGEST\",\n"
            + "        \"creationTimeOffset\": \"PT2H\",\n"
            + "        \"datasetTimestampOffset\": \"PT26H\"\n"
            + "      },\n"
            + "      \"actions\": []\n"
            + "    },\n"
            + "    {\n"
            + "      \"id\": \"unique-ratio-29f3ef1c-monitor\",\n"
            + "      \"analyzerIds\": [\n"
            + "        \"unique-ratio-29f3ef1c\"\n"
            + "      ],\n"
            + "      \"schedule\": {\n"
            + "        \"type\": \"immediate\"\n"
            + "      },\n"
            + "      \"severity\": 3,\n"
            + "      \"mode\": {\n"
            + "        \"type\": \"DIGEST\",\n"
            + "        \"creationTimeOffset\": \"PT2H\",\n"
            + "        \"datasetTimestampOffset\": \"PT26H\"\n"
            + "      },\n"
            + "      \"actions\": []\n"
            + "    },\n"
            + "    {\n"
            + "      \"id\": \"missing-profile-analyzer-monitor\",\n"
            + "      \"analyzerIds\": [\n"
            + "        \"missing-profile-analyzer\"\n"
            + "      ],\n"
            + "      \"schedule\": {\n"
            + "        \"type\": \"immediate\"\n"
            + "      },\n"
            + "      \"severity\": 4,\n"
            + "      \"mode\": {\n"
            + "        \"type\": \"DIGEST\",\n"
            + "        \"creationTimeOffset\": \"PT2H\",\n"
            + "        \"datasetTimestampOffset\": \"P2D\"\n"
            + "      },\n"
            + "      \"actions\": [\n"
            + "        {\n"
            + "          \"type\": \"global\",\n"
            + "          \"target\": \"pagerDuty\"\n"
            + "        }\n"
            + "      ]\n"
            + "    },\n"
            + "    {\n"
            + "      \"id\": \"inferred-data-type-33ee413a-monitor\",\n"
            + "      \"displayName\": \"inferred-data-type-33ee413a-monitor\",\n"
            + "      \"analyzerIds\": [\n"
            + "        \"inferred-data-type-33ee413a\"\n"
            + "      ],\n"
            + "      \"schedule\": {\n"
            + "        \"type\": \"immediate\"\n"
            + "      },\n"
            + "      \"severity\": 2,\n"
            + "      \"mode\": {\n"
            + "        \"type\": \"DIGEST\",\n"
            + "        \"creationTimeOffset\": \"P1D\",\n"
            + "        \"datasetTimestampOffset\": \"P7D\"\n"
            + "      },\n"
            + "      \"actions\": [],\n"
            + "      \"metadata\": {\n"
            + "        \"schemaVersion\": 1,\n"
            + "        \"author\": \"system\",\n"
            + "        \"updatedTimestamp\": 1662584946023,\n"
            + "        \"version\": 1\n"
            + "      }\n"
            + "    },\n"
            + "    {\n"
            + "      \"id\": \"old-tan-loris-9807\",\n"
            + "      \"displayName\": \"frequent_items_drift-monitor\",\n"
            + "      \"analyzerIds\": [\n"
            + "        \"old-tan-loris-9807-analyzer\"\n"
            + "      ],\n"
            + "      \"schedule\": {\n"
            + "        \"type\": \"immediate\"\n"
            + "      },\n"
            + "      \"severity\": 3,\n"
            + "      \"mode\": {\n"
            + "        \"type\": \"DIGEST\",\n"
            + "        \"creationTimeOffset\": \"P1D\",\n"
            + "        \"datasetTimestampOffset\": \"P7D\"\n"
            + "      },\n"
            + "      \"actions\": [\n"
            + "        {\n"
            + "          \"type\": \"global\",\n"
            + "          \"target\": \"email\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"type\": \"global\",\n"
            + "          \"target\": \"slack\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"type\": \"global\",\n"
            + "          \"target\": \"pagerDuty\"\n"
            + "        }\n"
            + "      ],\n"
            + "      \"metadata\": {\n"
            + "        \"schemaVersion\": 1,\n"
            + "        \"author\": \"system\",\n"
            + "        \"updatedTimestamp\": 1662675399914,\n"
            + "        \"version\": 1\n"
            + "      }\n"
            + "    }\n"
            + "  ],\n"
            + "  \"entitySchema\": {\n"
            + "    \"metadata\": {\n"
            + "      \"author\": \"system\",\n"
            + "      \"version\": 3,\n"
            + "      \"updatedTimestamp\": 1662673262031\n"
            + "    },\n"
            + "    \"columns\": {\n"
            + "      \"collection_recovery_fee\": {\n"
            + "        \"discreteness\": \"continuous\",\n"
            + "        \"dataType\": \"fractional\",\n"
            + "        \"classifier\": \"input\"\n"
            + "      },\n"
            + "      \"acc_now_delinq\": {\n"
            + "        \"discreteness\": \"continuous\",\n"
            + "        \"dataType\": \"fractional\",\n"
            + "        \"classifier\": \"input\"\n"
            + "      },\n"
            + "      \"num_sats\": {\n"
            + "        \"discreteness\": \"continuous\",\n"
            + "        \"dataType\": \"fractional\",\n"
            + "        \"classifier\": \"input\"\n"
            + "      },\n"
            + "      \"total_rec_int\": {\n"
            + "        \"discreteness\": \"continuous\",\n"
            + "        \"dataType\": \"fractional\",\n"
            + "        \"classifier\": \"input\"\n"
            + "      },\n"
            + "      \"mths_since_recent_revol_delinq\": {\n"
            + "        \"discreteness\": \"continuous\",\n"
            + "        \"dataType\": \"fractional\",\n"
            + "        \"classifier\": \"input\"\n"
            + "      },\n"
            + "      \"zip_code\": {\n"
            + "        \"discreteness\": \"discrete\",\n"
            + "        \"dataType\": \"string\",\n"
            + "        \"classifier\": \"input\"\n"
            + "      },\n"
            + "      \"initial_list_status\": {\n"
            + "        \"discreteness\": \"discrete\",\n"
            + "        \"dataType\": \"string\",\n"
            + "        \"classifier\": \"input\"\n"
            + "      },\n"
            + "      \"delinq_2yrs\": {\n"
            + "        \"discreteness\": \"continuous\",\n"
            + "        \"dataType\": \"fractional\",\n"
            + "        \"classifier\": \"input\"\n"
            + "      },\n"
            + "      \"debt_settlement_flag\": {\n"
            + "        \"discreteness\": \"discrete\",\n"
            + "        \"dataType\": \"string\",\n"
            + "        \"classifier\": \"input\"\n"
            + "      },\n"
            + "      \"last_credit_pull_d\": {\n"
            + "        \"discreteness\": \"discrete\",\n"
            + "        \"dataType\": \"string\",\n"
            + "        \"classifier\": \"input\"\n"
            + "      },\n"
            + "      \"emp_length\": {\n"
            + "        \"discreteness\": \"discrete\",\n"
            + "        \"dataType\": \"string\",\n"
            + "        \"classifier\": \"input\"\n"
            + "      },\n"
            + "      \"num_actv_rev_tl\": {\n"
            + "        \"discreteness\": \"continuous\",\n"
            + "        \"dataType\": \"fractional\",\n"
            + "        \"classifier\": \"input\"\n"
            + "      },\n"
            + "      \"last_fico_range_low\": {\n"
            + "        \"discreteness\": \"continuous\",\n"
            + "        \"dataType\": \"fractional\",\n"
            + "        \"classifier\": \"input\"\n"
            + "      },\n"
            + "      \"num_tl_op_past_12m\": {\n"
            + "        \"discreteness\": \"continuous\",\n"
            + "        \"dataType\": \"fractional\",\n"
            + "        \"classifier\": \"input\"\n"
            + "      },\n"
            + "      \"mo_sin_old_il_acct\": {\n"
            + "        \"discreteness\": \"continuous\",\n"
            + "        \"dataType\": \"fractional\",\n"
            + "        \"classifier\": \"input\"\n"
            + "      },\n"
            + "      \"home_ownership\": {\n"
            + "        \"discreteness\": \"discrete\",\n"
            + "        \"dataType\": \"string\",\n"
            + "        \"classifier\": \"input\"\n"
            + "      },\n"
            + "      \"pred_credit_risk (output)\": {\n"
            + "        \"discreteness\": \"continuous\",\n"
            + "        \"dataType\": \"fractional\",\n"
            + "        \"classifier\": \"output\"\n"
            + "      },\n"
            + "      \"revol_util\": {\n"
            + "        \"discreteness\": \"continuous\",\n"
            + "        \"dataType\": \"fractional\",\n"
            + "        \"classifier\": \"input\"\n"
            + "      },\n"
            + "      \"num_op_rev_tl\": {\n"
            + "        \"discreteness\": \"continuous\",\n"
            + "        \"dataType\": \"fractional\",\n"
            + "        \"classifier\": \"input\"\n"
            + "      },\n"
            + "      \"num_bc_tl\": {\n"
            + "        \"discreteness\": \"continuous\",\n"
            + "        \"dataType\": \"fractional\",\n"
            + "        \"classifier\": \"input\"\n"
            + "      },\n"
            + "      \"grade\": {\n"
            + "        \"discreteness\": \"discrete\",\n"
            + "        \"dataType\": \"string\",\n"
            + "        \"classifier\": \"input\"\n"
            + "      },\n"
            + "      \"disbursement_method\": {\n"
            + "        \"discreteness\": \"discrete\",\n"
            + "        \"dataType\": \"string\",\n"
            + "        \"classifier\": \"input\"\n"
            + "      },\n"
            + "      \"loan_amnt\": {\n"
            + "        \"discreteness\": \"continuous\",\n"
            + "        \"dataType\": \"fractional\",\n"
            + "        \"classifier\": \"input\"\n"
            + "      },\n"
            + "      \"annual_inc_joint\": {\n"
            + "        \"discreteness\": \"continuous\",\n"
            + "        \"dataType\": \"fractional\",\n"
            + "        \"classifier\": \"input\"\n"
            + "      },\n"
            + "      \"hardship_flag\": {\n"
            + "        \"discreteness\": \"discrete\",\n"
            + "        \"dataType\": \"string\",\n"
            + "        \"classifier\": \"input\"\n"
            + "      },\n"
            + "      \"tot_hi_cred_lim\": {\n"
            + "        \"discreteness\": \"continuous\",\n"
            + "        \"dataType\": \"fractional\",\n"
            + "        \"classifier\": \"input\"\n"
            + "      },\n"
            + "      \"issue_d\": {\n"
            + "        \"discreteness\": \"discrete\",\n"
            + "        \"dataType\": \"unknown\",\n"
            + "        \"classifier\": \"input\"\n"
            + "      },\n"
            + "      \"mths_since_recent_bc_dlq\": {\n"
            + "        \"discreteness\": \"continuous\",\n"
            + "        \"dataType\": \"fractional\",\n"
            + "        \"classifier\": \"input\"\n"
            + "      },\n"
            + "      \"mths_since_recent_inq\": {\n"
            + "        \"discreteness\": \"continuous\",\n"
            + "        \"dataType\": \"fractional\",\n"
            + "        \"classifier\": \"input\"\n"
            + "      },\n"
            + "      \"inq_last_6mths\": {\n"
            + "        \"discreteness\": \"continuous\",\n"
            + "        \"dataType\": \"fractional\",\n"
            + "        \"classifier\": \"input\"\n"
            + "      },\n"
            + "      \"num_accts_ever_120_pd\": {\n"
            + "        \"discreteness\": \"continuous\",\n"
            + "        \"dataType\": \"fractional\",\n"
            + "        \"classifier\": \"input\"\n"
            + "      },\n"
            + "      \"verification_status_joint\": {\n"
            + "        \"discreteness\": \"discrete\",\n"
            + "        \"dataType\": \"string\",\n"
            + "        \"classifier\": \"input\"\n"
            + "      },\n"
            + "      \"recoveries\": {\n"
            + "        \"discreteness\": \"continuous\",\n"
            + "        \"dataType\": \"fractional\",\n"
            + "        \"classifier\": \"input\"\n"
            + "      },\n"
            + "      \"pub_rec_bankruptcies\": {\n"
            + "        \"discreteness\": \"continuous\",\n"
            + "        \"dataType\": \"fractional\",\n"
            + "        \"classifier\": \"input\"\n"
            + "      },\n"
            + "      \"pymnt_plan\": {\n"
            + "        \"discreteness\": \"discrete\",\n"
            + "        \"dataType\": \"string\",\n"
            + "        \"classifier\": \"input\"\n"
            + "      },\n"
            + "      \"out_prncp_inv\": {\n"
            + "        \"discreteness\": \"continuous\",\n"
            + "        \"dataType\": \"fractional\",\n"
            + "        \"classifier\": \"input\"\n"
            + "      },\n"
            + "      \"mths_since_recent_bc\": {\n"
            + "        \"discreteness\": \"continuous\",\n"
            + "        \"dataType\": \"fractional\",\n"
            + "        \"classifier\": \"input\"\n"
            + "      },\n"
            + "      \"term\": {\n"
            + "        \"discreteness\": \"discrete\",\n"
            + "        \"dataType\": \"string\",\n"
            + "        \"classifier\": \"input\"\n"
            + "      },\n"
            + "      \"mths_since_last_delinq\": {\n"
            + "        \"discreteness\": \"continuous\",\n"
            + "        \"dataType\": \"fractional\",\n"
            + "        \"classifier\": \"input\"\n"
            + "      },\n"
            + "      \"num_tl_30dpd\": {\n"
            + "        \"discreteness\": \"continuous\",\n"
            + "        \"dataType\": \"fractional\",\n"
            + "        \"classifier\": \"input\"\n"
            + "      },\n"
            + "      \"loan_status\": {\n"
            + "        \"discreteness\": \"discrete\",\n"
            + "        \"dataType\": \"string\",\n"
            + "        \"classifier\": \"input\"\n"
            + "      },\n"
            + "      \"last_pymnt_amnt\": {\n"
            + "        \"discreteness\": \"continuous\",\n"
            + "        \"dataType\": \"fractional\",\n"
            + "        \"classifier\": \"input\"\n"
            + "      },\n"
            + "      \"num_actv_bc_tl\": {\n"
            + "        \"discreteness\": \"continuous\",\n"
            + "        \"dataType\": \"fractional\",\n"
            + "        \"classifier\": \"input\"\n"
            + "      },\n"
            + "      \"mths_since_last_major_derog\": {\n"
            + "        \"discreteness\": \"continuous\",\n"
            + "        \"dataType\": \"fractional\",\n"
            + "        \"classifier\": \"input\"\n"
            + "      },\n"
            + "      \"emp_title\": {\n"
            + "        \"discreteness\": \"discrete\",\n"
            + "        \"dataType\": \"string\",\n"
            + "        \"classifier\": \"input\"\n"
            + "      },\n"
            + "      \"total_rec_late_fee\": {\n"
            + "        \"discreteness\": \"continuous\",\n"
            + "        \"dataType\": \"fractional\",\n"
            + "        \"classifier\": \"input\"\n"
            + "      },\n"
            + "      \"url\": {\n"
            + "        \"discreteness\": \"discrete\",\n"
            + "        \"dataType\": \"string\",\n"
            + "        \"classifier\": \"input\"\n"
            + "      },\n"
            + "      \"bc_open_to_buy\": {\n"
            + "        \"discreteness\": \"continuous\",\n"
            + "        \"dataType\": \"fractional\",\n"
            + "        \"classifier\": \"input\"\n"
            + "      },\n"
            + "      \"addr_state\": {\n"
            + "        \"discreteness\": \"discrete\",\n"
            + "        \"dataType\": \"string\",\n"
            + "        \"classifier\": \"input\"\n"
            + "      },\n"
            + "      \"mo_sin_rcnt_rev_tl_op\": {\n"
            + "        \"discreteness\": \"continuous\",\n"
            + "        \"dataType\": \"fractional\",\n"
            + "        \"classifier\": \"input\"\n"
            + "      },\n"
            + "      \"num_il_tl\": {\n"
            + "        \"discreteness\": \"continuous\",\n"
            + "        \"dataType\": \"fractional\",\n"
            + "        \"classifier\": \"input\"\n"
            + "      },\n"
            + "      \"total_bal_ex_mort\": {\n"
            + "        \"discreteness\": \"continuous\",\n"
            + "        \"dataType\": \"fractional\",\n"
            + "        \"classifier\": \"input\"\n"
            + "      },\n"
            + "      \"chargeoff_within_12_mths\": {\n"
            + "        \"discreteness\": \"continuous\",\n"
            + "        \"dataType\": \"fractional\",\n"
            + "        \"classifier\": \"input\"\n"
            + "      },\n"
            + "      \"num_rev_accts\": {\n"
            + "        \"discreteness\": \"continuous\",\n"
            + "        \"dataType\": \"fractional\",\n"
            + "        \"classifier\": \"input\"\n"
            + "      },\n"
            + "      \"tot_cur_bal\": {\n"
            + "        \"discreteness\": \"continuous\",\n"
            + "        \"dataType\": \"fractional\",\n"
            + "        \"classifier\": \"input\"\n"
            + "      },\n"
            + "      \"total_bc_limit\": {\n"
            + "        \"discreteness\": \"continuous\",\n"
            + "        \"dataType\": \"fractional\",\n"
            + "        \"classifier\": \"input\"\n"
            + "      },\n"
            + "      \"fico_range_high\": {\n"
            + "        \"discreteness\": \"continuous\",\n"
            + "        \"dataType\": \"fractional\",\n"
            + "        \"classifier\": \"input\"\n"
            + "      },\n"
            + "      \"out_prncp\": {\n"
            + "        \"discreteness\": \"continuous\",\n"
            + "        \"dataType\": \"fractional\",\n"
            + "        \"classifier\": \"input\"\n"
            + "      },\n"
            + "      \"acc_open_past_24mths\": {\n"
            + "        \"discreteness\": \"continuous\",\n"
            + "        \"dataType\": \"fractional\",\n"
            + "        \"classifier\": \"input\"\n"
            + "      },\n"
            + "      \"next_pymnt_d\": {\n"
            + "        \"discreteness\": \"discrete\",\n"
            + "        \"dataType\": \"string\",\n"
            + "        \"classifier\": \"input\"\n"
            + "      },\n"
            + "      \"last_pymnt_d\": {\n"
            + "        \"discreteness\": \"discrete\",\n"
            + "        \"dataType\": \"string\",\n"
            + "        \"classifier\": \"input\"\n"
            + "      },\n"
            + "      \"num_tl_90g_dpd_24m\": {\n"
            + "        \"discreteness\": \"continuous\",\n"
            + "        \"dataType\": \"fractional\",\n"
            + "        \"classifier\": \"input\"\n"
            + "      },\n"
            + "      \"total_acc\": {\n"
            + "        \"discreteness\": \"continuous\",\n"
            + "        \"dataType\": \"fractional\",\n"
            + "        \"classifier\": \"input\"\n"
            + "      },\n"
            + "      \"int_rate\": {\n"
            + "        \"discreteness\": \"continuous\",\n"
            + "        \"dataType\": \"fractional\",\n"
            + "        \"classifier\": \"input\"\n"
            + "      },\n"
            + "      \"avg_cur_bal\": {\n"
            + "        \"discreteness\": \"continuous\",\n"
            + "        \"dataType\": \"fractional\",\n"
            + "        \"classifier\": \"input\"\n"
            + "      },\n"
            + "      \"annual_inc\": {\n"
            + "        \"discreteness\": \"continuous\",\n"
            + "        \"dataType\": \"fractional\",\n"
            + "        \"classifier\": \"input\"\n"
            + "      },\n"
            + "      \"pct_tl_nvr_dlq\": {\n"
            + "        \"discreteness\": \"continuous\",\n"
            + "        \"dataType\": \"fractional\",\n"
            + "        \"classifier\": \"input\"\n"
            + "      },\n"
            + "      \"funded_amnt_inv\": {\n"
            + "        \"discreteness\": \"continuous\",\n"
            + "        \"dataType\": \"fractional\",\n"
            + "        \"classifier\": \"input\"\n"
            + "      },\n"
            + "      \"installment\": {\n"
            + "        \"discreteness\": \"continuous\",\n"
            + "        \"dataType\": \"fractional\",\n"
            + "        \"classifier\": \"input\"\n"
            + "      },\n"
            + "      \"earliest_cr_line\": {\n"
            + "        \"discreteness\": \"discrete\",\n"
            + "        \"dataType\": \"string\",\n"
            + "        \"classifier\": \"input\"\n"
            + "      },\n"
            + "      \"num_tl_120dpd_2m\": {\n"
            + "        \"discreteness\": \"continuous\",\n"
            + "        \"dataType\": \"fractional\",\n"
            + "        \"classifier\": \"input\"\n"
            + "      },\n"
            + "      \"total_rec_prncp\": {\n"
            + "        \"discreteness\": \"continuous\",\n"
            + "        \"dataType\": \"fractional\",\n"
            + "        \"classifier\": \"input\"\n"
            + "      },\n"
            + "      \"last_fico_range_high\": {\n"
            + "        \"discreteness\": \"continuous\",\n"
            + "        \"dataType\": \"fractional\",\n"
            + "        \"classifier\": \"input\"\n"
            + "      },\n"
            + "      \"pub_rec\": {\n"
            + "        \"discreteness\": \"continuous\",\n"
            + "        \"dataType\": \"fractional\",\n"
            + "        \"classifier\": \"input\"\n"
            + "      },\n"
            + "      \"tot_coll_amt\": {\n"
            + "        \"discreteness\": \"continuous\",\n"
            + "        \"dataType\": \"fractional\",\n"
            + "        \"classifier\": \"input\"\n"
            + "      },\n"
            + "      \"percent_bc_gt_75\": {\n"
            + "        \"discreteness\": \"continuous\",\n"
            + "        \"dataType\": \"fractional\",\n"
            + "        \"classifier\": \"input\"\n"
            + "      },\n"
            + "      \"desc\": {\n"
            + "        \"discreteness\": \"discrete\",\n"
            + "        \"dataType\": \"unknown\",\n"
            + "        \"classifier\": \"input\"\n"
            + "      },\n"
            + "      \"funded_amnt\": {\n"
            + "        \"discreteness\": \"continuous\",\n"
            + "        \"dataType\": \"fractional\",\n"
            + "        \"classifier\": \"input\"\n"
            + "      },\n"
            + "      \"total_rev_hi_lim\": {\n"
            + "        \"discreteness\": \"continuous\",\n"
            + "        \"dataType\": \"fractional\",\n"
            + "        \"classifier\": \"input\"\n"
            + "      },\n"
            + "      \"delinq_amnt\": {\n"
            + "        \"discreteness\": \"continuous\",\n"
            + "        \"dataType\": \"fractional\",\n"
            + "        \"classifier\": \"input\"\n"
            + "      },\n"
            + "      \"bc_util\": {\n"
            + "        \"discreteness\": \"continuous\",\n"
            + "        \"dataType\": \"fractional\",\n"
            + "        \"classifier\": \"input\"\n"
            + "      },\n"
            + "      \"mo_sin_rcnt_tl\": {\n"
            + "        \"discreteness\": \"continuous\",\n"
            + "        \"dataType\": \"fractional\",\n"
            + "        \"classifier\": \"input\"\n"
            + "      },\n"
            + "      \"application_type\": {\n"
            + "        \"discreteness\": \"discrete\",\n"
            + "        \"dataType\": \"string\",\n"
            + "        \"classifier\": \"input\"\n"
            + "      },\n"
            + "      \"tax_liens\": {\n"
            + "        \"discreteness\": \"continuous\",\n"
            + "        \"dataType\": \"fractional\",\n"
            + "        \"classifier\": \"input\"\n"
            + "      },\n"
            + "      \"mths_since_last_record\": {\n"
            + "        \"discreteness\": \"continuous\",\n"
            + "        \"dataType\": \"fractional\",\n"
            + "        \"classifier\": \"input\"\n"
            + "      },\n"
            + "      \"title\": {\n"
            + "        \"discreteness\": \"discrete\",\n"
            + "        \"dataType\": \"string\",\n"
            + "        \"classifier\": \"input\"\n"
            + "      },\n"
            + "      \"mo_sin_old_rev_tl_op\": {\n"
            + "        \"discreteness\": \"continuous\",\n"
            + "        \"dataType\": \"fractional\",\n"
            + "        \"classifier\": \"input\"\n"
            + "      },\n"
            + "      \"all_util\": {\n"
            + "        \"discreteness\": \"continuous\",\n"
            + "        \"dataType\": \"fractional\",\n"
            + "        \"classifier\": \"input\"\n"
            + "      },\n"
            + "      \"policy_code\": {\n"
            + "        \"discreteness\": \"continuous\",\n"
            + "        \"dataType\": \"fractional\",\n"
            + "        \"classifier\": \"input\"\n"
            + "      },\n"
            + "      \"dti\": {\n"
            + "        \"discreteness\": \"continuous\",\n"
            + "        \"dataType\": \"fractional\",\n"
            + "        \"classifier\": \"input\"\n"
            + "      },\n"
            + "      \"num_bc_sats\": {\n"
            + "        \"discreteness\": \"continuous\",\n"
            + "        \"dataType\": \"fractional\",\n"
            + "        \"classifier\": \"input\"\n"
            + "      },\n"
            + "      \"sub_grade\": {\n"
            + "        \"discreteness\": \"discrete\",\n"
            + "        \"dataType\": \"string\",\n"
            + "        \"classifier\": \"input\"\n"
            + "      },\n"
            + "      \"total_pymnt\": {\n"
            + "        \"discreteness\": \"continuous\",\n"
            + "        \"dataType\": \"fractional\",\n"
            + "        \"classifier\": \"input\"\n"
            + "      },\n"
            + "      \"num_rev_tl_bal_gt_0\": {\n"
            + "        \"discreteness\": \"continuous\",\n"
            + "        \"dataType\": \"fractional\",\n"
            + "        \"classifier\": \"input\"\n"
            + "      },\n"
            + "      \"mort_acc\": {\n"
            + "        \"discreteness\": \"continuous\",\n"
            + "        \"dataType\": \"fractional\",\n"
            + "        \"classifier\": \"input\"\n"
            + "      },\n"
            + "      \"total_pymnt_inv\": {\n"
            + "        \"discreteness\": \"continuous\",\n"
            + "        \"dataType\": \"fractional\",\n"
            + "        \"classifier\": \"input\"\n"
            + "      },\n"
            + "      \"fico_range_low\": {\n"
            + "        \"discreteness\": \"continuous\",\n"
            + "        \"dataType\": \"fractional\",\n"
            + "        \"classifier\": \"input\"\n"
            + "      },\n"
            + "      \"total_il_high_credit_limit\": {\n"
            + "        \"discreteness\": \"continuous\",\n"
            + "        \"dataType\": \"fractional\",\n"
            + "        \"classifier\": \"input\"\n"
            + "      },\n"
            + "      \"revol_bal\": {\n"
            + "        \"discreteness\": \"continuous\",\n"
            + "        \"dataType\": \"fractional\",\n"
            + "        \"classifier\": \"input\"\n"
            + "      },\n"
            + "      \"dti_joint\": {\n"
            + "        \"discreteness\": \"continuous\",\n"
            + "        \"dataType\": \"fractional\",\n"
            + "        \"classifier\": \"input\"\n"
            + "      },\n"
            + "      \"open_acc\": {\n"
            + "        \"discreteness\": \"continuous\",\n"
            + "        \"dataType\": \"fractional\",\n"
            + "        \"classifier\": \"input\"\n"
            + "      },\n"
            + "      \"collections_12_mths_ex_med\": {\n"
            + "        \"discreteness\": \"continuous\",\n"
            + "        \"dataType\": \"fractional\",\n"
            + "        \"classifier\": \"input\"\n"
            + "      }\n"
            + "    }\n"
            + "  },\n"
            + "  \"weightConfig\": {\n"
            + "    \"metadata\": {\n"
            + "      \"author\": \"system\",\n"
            + "      \"version\": 3,\n"
            + "      \"updatedTimestamp\": 1662742912035\n"
            + "    },\n"
            + "    \"segmentWeights\": [\n"
            + "      {\n"
            + "        \"segment\": null,\n"
            + "        \"weights\": {\n"
            + "          \"collection_recovery_fee\": 0.12,\n"
            + "          \"acc_now_delinq\": 0.32,\n"
            + "          \"num_sats\": 0.5\n"
            + "        }\n"
            + "      }\n"
            + "    ]\n"
            + "  }\n"
            + "}";

    val conf = MonitorConfigV3JsonSerde.parseMonitorConfigV3(json);
    val wc = conf.getWeightConfig();
    assertEquals(1, wc.getSegmentWeights().size());
    assertThat(
        wc.getSegmentWeights().get(0).getWeights().get("collection_recovery_fee"),
        closeTo(.12, 0.0001));
  }
}
