package ai.whylabs.batch;

import static junit.framework.Assert.assertEquals;
import static org.testng.AssertJUnit.assertNotNull;
import static org.testng.AssertJUnit.assertNull;

import ai.whylabs.core.configV3.structure.MonitorConfigV3;
import ai.whylabs.core.configV3.structure.enums.DataType;
import ai.whylabs.core.serde.MonitorConfigV3JsonSerde;
import ai.whylabs.core.utils.ClasspathFileLoader;
import java.time.ZoneOffset;
import java.time.ZonedDateTime;
import lombok.val;
import org.testng.annotations.Test;

@Test
public class MonitorConfigV3Test extends BaseTest {

  @Test
  public void testBinner() {

    val dt1 = ZonedDateTime.of(2022, 2, 15, 1, 2, 35, 0, ZoneOffset.UTC);
    val b =
        MonitorConfigV3.builder()
            .orgId("org-11")
            .updatedTs(dt1.toInstant().toEpochMilli())
            .datasetId("model-0");
  }

  /*@Test TODO: We no longer require rollup to be set, but this test might be good for other bad scenarios we cook up
  public void testBadJsonConfigProducesMonitorRunRow() {
    val dt1 =
        ZonedDateTime.of(2022, 2, 15, 1, 2, 35, 0, ZoneOffset.UTC).truncatedTo(ChronoUnit.HOURS);
    val b =
        MonitorConfigV3.builder()
            .orgId("org-11")
            .updatedTs(dt1.toInstant().toEpochMilli())
            .datasetId("model-0");

    String json =
        "{\"id\":\"12345678-1234-5678-1234-567812345678\",\"orgId\":\"org-1\",\"schemaVersion\":1,\"entityId\":\"model-1\",\"granularity\":\"daily\",\"entitySchema\":{\"annual_inc\":{\"discreteness\":\"discrete\",\"dataType\":\"integral\",\"classifier\":\"input\",\"weight\":1},\"prediction\":{\"discreteness\":\"discrete\",\"dataType\":\"integral\",\"classifier\":\"output\",\"weight\":1}},\"analyzers\":[{\"schemaVersion\":1,\"id\":\"numerical_drift-analyzer\",\"schedule\":{\"cron\":\"0 * * * * *\"},\"baseline\":{\"type\":\"TrailingWindow\",\"size\":14},\"target\":{\"level\":\"field\",\"metric\":\"histogram\",\"allowedFields\":[\"group:continuous\"],\"segments\":[{\"tags\":[]}],\"batchOffset\":1,\"maxDelayBatchCount\":14},\"config\":{\"version\":1,\"type\":\"drift\",\"mode\":\"continuous\",\"algorithm\":\"hellinger\",\"threshold\":0.5}},{\"schemaVersion\":1,\"id\":\"frequent_items_drift-analyzer\",\"schedule\":{\"cron\":\"0 * * * * *\"},\"baseline\":{\"type\":\"TrailingWindow\",\"size\":14},\"target\":{\"level\":\"field\",\"metric\":\"frequent_items\",\"allowedFields\":[\"group:discrete\"],\"segments\":[{\"tags\":[]}],\"batchOffset\":1,\"maxDelayBatchCount\":14},\"config\":{\"version\":1,\"type\":\"drift\",\"mode\":\"continuous\",\"algorithm\":\"hellinger\",\"threshold\":0.5}},{\"schemaVersion\":1,\"id\":\"drift-analyzer\",\"schedule\":{\"cron\":\"0 * * * * *\"},\"baseline\":{\"type\":\"TrailingWindow\",\"size\":14},\"target\":{\"level\":\"dataset\",\"metric\":\"classification.f1\",\"segments\":[{\"tags\":[]}],\"batchOffset\":1,\"maxDelayBatchCount\":14},\"config\":{\"version\":1,\"type\":\"stddev\",\"factor\":5,\"minBatchSize\":7}}],\"monitors\":[{\"id\":\"drift-monitor-1\",\"analyzerIds\":[\"numerical_drift-analyzer\",\"frequent_items_drift-analyzer\"],\"schedule\":{\"cron\":\"0 0 * * * *\"},\"severity\":4,\"mode\":{\"type\":\"DIGEST\",\"filter\":{\"minAlertCount\":20},\"creationTimeOffset\":\"1 day\",\"datasetTimestampOffset\":\"7 days\"},\"actions\":[{\"type\":\"global\",\"target\":\"action-xyz\"},{\"type\":\"email\",\"target\":\"demo@whylabs.ai\"},{\"type\":\"slack\",\"target\":\"https://demo.com\"}]},{\"id\":\"drift-monitor-important-features-2\",\"analyzerIds\":[\"numerical_drift-analyzer\",\"frequent_items_drift-analyzer\"],\"schedule\":{\"cron\":\"0 0 * * * *\"},\"severity\":2,\"mode\":{\"type\":\"EVERY_ANOMALY\",\"filter\":{\"excludeFields\":[\"very_noisy\"],\"minWeight\":0.5,\"minRankByWeight\":10}},\"actions\":[{\"type\":\"global\",\"target\":\"action-xyz\"},{\"type\":\"email\",\"target\":\"demo@whylabs.ai\"},{\"type\":\"slack\",\"target\":\"https://demo.com\"}]},{\"id\":\"f1-monitor-1\",\"analyzerIds\":[\"drift-analyzer\"],\"schedule\":{\"cron\":\"0 0 * * * *\"},\"severity\":2,\"mode\":{\"type\":\"EVERY_ANOMALY\"},\"actions\":[{\"type\":\"global\",\"target\":\"action-xyz\"},{\"type\":\"email\",\"target\":\"demo@whylabs.ai\"}]}]}";
    // val conf = MonitorConfigV3JsonSerde.parseMonitorConfigV3(json);
    val row = MonitorConfigV3Row.builder().jsonConf(json).build();

    val out = new MonitorConfigValidationCheckToMonitorRun(dt1, "blah", true).call(row);
    int c = 0;
    val badConfigs = Arrays.asList("numerical_drift-analyzer", "frequent_items_drift-analyzer");
    while (out.hasNext()) {
      c++;
      val next = out.next();
      assertTrue(badConfigs.contains(next.getAnalyzerId()));
    }
    assertEquals(2, c);
  }*/

  @Test
  public void testMissingDiscretness() {
    String json =
        "{\n"
            + "  \"orgId\": \"org-hURArx\",\n"
            + "  \"datasetId\": \"model-51\",\n"
            + "  \"granularity\": \"daily\",\n"
            + "  \"metadata\": {\n"
            + "    \"schemaVersion\": 1,\n"
            + "    \"author\": \"user_e284826512e5fad8892142dfa40639fb98e48b043a2b7c8735b4c99ed244e716\",\n"
            + "    \"updatedTimestamp\": 1701817820558,\n"
            + "    \"version\": 16\n"
            + "  },\n"
            + "  \"analyzers\": [\n"
            + "    {\n"
            + "      \"config\": {\n"
            + "        \"algorithm\": \"hellinger\",\n"
            + "        \"metric\": \"histogram\",\n"
            + "        \"type\": \"drift\",\n"
            + "        \"threshold\": 0.2,\n"
            + "        \"baseline\": {\n"
            + "          \"type\": \"TrailingWindow\",\n"
            + "          \"size\": 28\n"
            + "        }\n"
            + "      },\n"
            + "      \"id\": \"top-features-weekly-mlhub-feature-drift\",\n"
            + "      \"schedule\": {\n"
            + "        \"type\": \"fixed\",\n"
            + "        \"cadence\": \"weekly\"\n"
            + "      },\n"
            + "      \"targetMatrix\": {\n"
            + "        \"include\": [\n"
            + "          \"activation_connected_disabled_users_through_ssn_count_by_master_merchant_from_activation_master_merchant\"\n"
            + "        ],\n"
            + "        \"exclude\": [],\n"
            + "        \"segments\": [\n"
            + "          {\n"
            + "            \"tags\": []\n"
            + "          }\n"
            + "        ],\n"
            + "        \"type\": \"column\"\n"
            + "      }\n"
            + "    },\n"
            + "    {\n"
            + "      \"config\": {\n"
            + "        \"algorithm\": \"hellinger\",\n"
            + "        \"metric\": \"histogram\",\n"
            + "        \"type\": \"drift\",\n"
            + "        \"threshold\": 0.5,\n"
            + "        \"baseline\": {\n"
            + "          \"type\": \"TrailingWindow\",\n"
            + "          \"size\": 28\n"
            + "        }\n"
            + "      },\n"
            + "      \"id\": \"top-features-daily-mlhub-feature-drift\",\n"
            + "      \"schedule\": {\n"
            + "        \"type\": \"fixed\",\n"
            + "        \"cadence\": \"daily\"\n"
            + "      },\n"
            + "      \"targetMatrix\": {\n"
            + "        \"include\": [\n"
            + "          \"activation_connected_disabled_users_through_ssn_count_by_master_merchant_from_activation_master_merchant\"\n"
            + "        ],\n"
            + "        \"exclude\": [],\n"
            + "        \"segments\": [\n"
            + "          {\n"
            + "            \"tags\": []\n"
            + "          }\n"
            + "        ],\n"
            + "        \"type\": \"column\"\n"
            + "      }\n"
            + "    },\n"
            + "    {\n"
            + "      \"config\": {\n"
            + "        \"metric\": \"count_null_ratio\",\n"
            + "        \"type\": \"stddev\",\n"
            + "        \"factor\": 3,\n"
            + "        \"baseline\": {\n"
            + "          \"type\": \"TrailingWindow\",\n"
            + "          \"size\": 28\n"
            + "        }\n"
            + "      },\n"
            + "      \"id\": \"top-features-weekly-mlhub-missing-values\",\n"
            + "      \"schedule\": {\n"
            + "        \"type\": \"fixed\",\n"
            + "        \"cadence\": \"weekly\"\n"
            + "      },\n"
            + "      \"targetMatrix\": {\n"
            + "        \"include\": [\n"
            + "          \"activation_connected_disabled_users_through_ssn_count_by_master_merchant_from_activation_master_merchant\"\n"
            + "        ],\n"
            + "        \"exclude\": [],\n"
            + "        \"segments\": [\n"
            + "          {\n"
            + "            \"tags\": []\n"
            + "          }\n"
            + "        ],\n"
            + "        \"type\": \"column\"\n"
            + "      }\n"
            + "    },\n"
            + "    {\n"
            + "      \"config\": {\n"
            + "        \"algorithm\": \"hellinger\",\n"
            + "        \"metric\": \"histogram\",\n"
            + "        \"type\": \"drift\",\n"
            + "        \"threshold\": 0.4,\n"
            + "        \"baseline\": {\n"
            + "          \"type\": \"TrailingWindow\",\n"
            + "          \"size\": 28\n"
            + "        }\n"
            + "      },\n"
            + "      \"id\": \"significant-features-weekly-mlhub-feature-drift\",\n"
            + "      \"schedule\": {\n"
            + "        \"type\": \"fixed\",\n"
            + "        \"cadence\": \"weekly\"\n"
            + "      },\n"
            + "      \"targetMatrix\": {\n"
            + "        \"include\": [\n"
            + "          \"activation_connected_users_through_hard_asset_count_by_master_merchant_from_activation_master_merchant\",\n"
            + "          \"business_name_fraction_uppercase_by_master_merchant_from_activation_master_merchant\"\n"
            + "        ],\n"
            + "        \"exclude\": [],\n"
            + "        \"segments\": [\n"
            + "          {\n"
            + "            \"tags\": []\n"
            + "          }\n"
            + "        ],\n"
            + "        \"type\": \"column\"\n"
            + "      }\n"
            + "    },\n"
            + "    {\n"
            + "      \"config\": {\n"
            + "        \"algorithm\": \"hellinger\",\n"
            + "        \"metric\": \"histogram\",\n"
            + "        \"type\": \"drift\",\n"
            + "        \"threshold\": 1,\n"
            + "        \"baseline\": {\n"
            + "          \"type\": \"TrailingWindow\",\n"
            + "          \"size\": 28\n"
            + "        }\n"
            + "      },\n"
            + "      \"id\": \"significant-features-daily-mlhub-feature-drift\",\n"
            + "      \"schedule\": {\n"
            + "        \"type\": \"fixed\",\n"
            + "        \"cadence\": \"daily\"\n"
            + "      },\n"
            + "      \"targetMatrix\": {\n"
            + "        \"include\": [\n"
            + "          \"activation_connected_users_through_hard_asset_count_by_master_merchant_from_activation_master_merchant\",\n"
            + "          \"business_name_fraction_uppercase_by_master_merchant_from_activation_master_merchant\"\n"
            + "        ],\n"
            + "        \"exclude\": [],\n"
            + "        \"segments\": [\n"
            + "          {\n"
            + "            \"tags\": []\n"
            + "          }\n"
            + "        ],\n"
            + "        \"type\": \"column\"\n"
            + "      }\n"
            + "    }\n"
            + "  ],\n"
            + "  \"monitors\": [\n"
            + "    {\n"
            + "      \"id\": \"significant-features-daily-mlhub-feature-drift-monitor\",\n"
            + "      \"analyzerIds\": [\n"
            + "        \"significant-features-daily-mlhub-feature-drift\"\n"
            + "      ],\n"
            + "      \"schedule\": {\n"
            + "        \"type\": \"immediate\"\n"
            + "      },\n"
            + "      \"mode\": {\n"
            + "        \"type\": \"DIGEST\"\n"
            + "      },\n"
            + "      \"disabled\": false,\n"
            + "      \"actions\": []\n"
            + "    },\n"
            + "    {\n"
            + "      \"id\": \"significant-features-weekly-mlhub-feature-drift-monitor\",\n"
            + "      \"analyzerIds\": [\n"
            + "        \"significant-features-weekly-mlhub-feature-drift\"\n"
            + "      ],\n"
            + "      \"schedule\": {\n"
            + "        \"type\": \"immediate\"\n"
            + "      },\n"
            + "      \"mode\": {\n"
            + "        \"type\": \"DIGEST\"\n"
            + "      },\n"
            + "      \"disabled\": false,\n"
            + "      \"actions\": []\n"
            + "    },\n"
            + "    {\n"
            + "      \"id\": \"top-features-daily-mlhub-feature-drift-monitor\",\n"
            + "      \"analyzerIds\": [\n"
            + "        \"top-features-daily-mlhub-feature-drift\"\n"
            + "      ],\n"
            + "      \"schedule\": {\n"
            + "        \"type\": \"immediate\"\n"
            + "      },\n"
            + "      \"mode\": {\n"
            + "        \"type\": \"DIGEST\"\n"
            + "      },\n"
            + "      \"disabled\": false,\n"
            + "      \"actions\": []\n"
            + "    },\n"
            + "    {\n"
            + "      \"id\": \"top-features-weekly-mlhub-feature-drift-monitor\",\n"
            + "      \"analyzerIds\": [\n"
            + "        \"top-features-weekly-mlhub-feature-drift\"\n"
            + "      ],\n"
            + "      \"schedule\": {\n"
            + "        \"type\": \"immediate\"\n"
            + "      },\n"
            + "      \"mode\": {\n"
            + "        \"type\": \"DIGEST\"\n"
            + "      },\n"
            + "      \"disabled\": false,\n"
            + "      \"actions\": []\n"
            + "    },\n"
            + "    {\n"
            + "      \"id\": \"top-features-weekly-mlhub-missing-values-monitor\",\n"
            + "      \"analyzerIds\": [\n"
            + "        \"top-features-weekly-mlhub-missing-values\"\n"
            + "      ],\n"
            + "      \"schedule\": {\n"
            + "        \"type\": \"immediate\"\n"
            + "      },\n"
            + "      \"mode\": {\n"
            + "        \"type\": \"DIGEST\"\n"
            + "      },\n"
            + "      \"disabled\": false,\n"
            + "      \"actions\": []\n"
            + "    }\n"
            + "  ],\n"
            + "  \"entitySchema\": {\n"
            + "    \"metadata\": {\n"
            + "      \"author\": \"system\",\n"
            + "      \"version\": 25,\n"
            + "      \"updatedTimestamp\": 1713157210746\n"
            + "    },\n"
            + "    \"columns\": {\n"
            + "      \"output\": {\n"
            + "        \"discreteness\": \"continuous\",\n"
            + "        \"dataType\": \"fractional\",\n"
            + "        \"classifier\": \"output\",\n"
            + "        \"tags\": null\n"
            + "      },\n"
            + "      \"activation_connected_users_through_hard_asset_count_by_master_merchant_from_activation_master_merchant\": {\n"
            + "        \"discreteness\": \"\",\n"
            + "        \"dataType\": \"fractional\",\n"
            + "        \"classifier\": \"input\",\n"
            + "        \"tags\": null\n"
            + "      },\n"
            + "      \"business_name_fraction_uppercase_by_master_merchant_from_activation_master_merchant\": {\n"
            + "        \"discreteness\": \"continuous\",\n"
            + "        \"dataType\": \"fractional\",\n"
            + "        \"classifier\": \"input\",\n"
            + "        \"tags\": null\n"
            + "      },\n"
            + "      \"activation_connected_disabled_users_through_ssn_count_by_master_merchant_from_activation_master_merchant\": {\n"
            + "        \"discreteness\": \"continuous\",\n"
            + "        \"dataType\": \"fractional\",\n"
            + "        \"classifier\": \"input\",\n"
            + "        \"tags\": null\n"
            + "      },\n"
            + "      \"fake_column\": {\n"
            + "        \"discreteness\": \"continuous\",\n"
            + "        \"dataType\": \"fractional\",\n"
            + "        \"classifier\": \"input\",\n"
            + "        \"tags\": null\n"
            + "      },\n"
            + "      \"another_test_column\": {\n"
            + "        \"discreteness\": \"unknown\",\n"
            + "        \"dataType\": \"unknown\",\n"
            + "        \"classifier\": \"input\",\n"
            + "        \"tags\": null\n"
            + "      },\n"
            + "      \"another_test_column2\": {\n"
            + "        \"discreteness\": \"continuous\",\n"
            + "        \"dataType\": \"unknown\",\n"
            + "        \"classifier\": \"input\",\n"
            + "        \"tags\": null\n"
            + "      },\n"
            + "      \"unit_precision\": {\n"
            + "        \"discreteness\": \"continuous\",\n"
            + "        \"dataType\": \"fractional\",\n"
            + "        \"classifier\": \"input\",\n"
            + "        \"tags\": null\n"
            + "      },\n"
            + "      \"unit_flag_rate\": {\n"
            + "        \"discreteness\": \"continuous\",\n"
            + "        \"dataType\": \"fractional\",\n"
            + "        \"classifier\": \"input\",\n"
            + "        \"tags\": null\n"
            + "      },\n"
            + "      \"event_precision\": {\n"
            + "        \"discreteness\": \"continuous\",\n"
            + "        \"dataType\": \"fractional\",\n"
            + "        \"classifier\": \"input\",\n"
            + "        \"tags\": null\n"
            + "      },\n"
            + "      \"event_recall\": {\n"
            + "        \"discreteness\": \"continuous\",\n"
            + "        \"dataType\": \"fractional\",\n"
            + "        \"classifier\": \"input\",\n"
            + "        \"tags\": null\n"
            + "      },\n"
            + "      \"master_merchant_recall\": {\n"
            + "        \"discreteness\": \"continuous\",\n"
            + "        \"dataType\": \"fractional\",\n"
            + "        \"classifier\": \"input\",\n"
            + "        \"tags\": null\n"
            + "      },\n"
            + "      \"unit_recall\": {\n"
            + "        \"discreteness\": \"continuous\",\n"
            + "        \"dataType\": \"fractional\",\n"
            + "        \"classifier\": \"input\",\n"
            + "        \"tags\": null\n"
            + "      },\n"
            + "      \"master_merchant_precision\": {\n"
            + "        \"discreteness\": \"continuous\",\n"
            + "        \"dataType\": \"fractional\",\n"
            + "        \"classifier\": \"input\",\n"
            + "        \"tags\": null\n"
            + "      },\n"
            + "      \"event_flag_rate\": {\n"
            + "        \"discreteness\": \"continuous\",\n"
            + "        \"dataType\": \"fractional\",\n"
            + "        \"classifier\": \"input\",\n"
            + "        \"tags\": null\n"
            + "      },\n"
            + "      \"master_merchant_flag_rate\": {\n"
            + "        \"discreteness\": \"continuous\",\n"
            + "        \"dataType\": \"fractional\",\n"
            + "        \"classifier\": \"input\",\n"
            + "        \"tags\": null\n"
            + "      },\n"
            + "      \"output_master_merchant_recall\": {\n"
            + "        \"discreteness\": \"continuous\",\n"
            + "        \"dataType\": \"fractional\",\n"
            + "        \"classifier\": \"output\",\n"
            + "        \"tags\": null\n"
            + "      },\n"
            + "      \"output_event_flag_rate\": {\n"
            + "        \"discreteness\": \"continuous\",\n"
            + "        \"dataType\": \"fractional\",\n"
            + "        \"classifier\": \"output\",\n"
            + "        \"tags\": null\n"
            + "      },\n"
            + "      \"output_unit_flag_rate\": {\n"
            + "        \"discreteness\": \"continuous\",\n"
            + "        \"dataType\": \"fractional\",\n"
            + "        \"classifier\": \"output\",\n"
            + "        \"tags\": null\n"
            + "      },\n"
            + "      \"output_event_recall\": {\n"
            + "        \"discreteness\": \"continuous\",\n"
            + "        \"dataType\": \"fractional\",\n"
            + "        \"classifier\": \"output\",\n"
            + "        \"tags\": null\n"
            + "      },\n"
            + "      \"output_unit_recall\": {\n"
            + "        \"discreteness\": \"continuous\",\n"
            + "        \"dataType\": \"fractional\",\n"
            + "        \"classifier\": \"output\",\n"
            + "        \"tags\": null\n"
            + "      },\n"
            + "      \"output_master_merchant_flag_rate\": {\n"
            + "        \"discreteness\": \"continuous\",\n"
            + "        \"dataType\": \"fractional\",\n"
            + "        \"classifier\": \"output\",\n"
            + "        \"tags\": null\n"
            + "      },\n"
            + "      \"output_unit_precision\": {\n"
            + "        \"discreteness\": \"continuous\",\n"
            + "        \"dataType\": \"fractional\",\n"
            + "        \"classifier\": \"output\",\n"
            + "        \"tags\": null\n"
            + "      },\n"
            + "      \"output_event_precision\": {\n"
            + "        \"discreteness\": \"continuous\",\n"
            + "        \"dataType\": \"fractional\",\n"
            + "        \"classifier\": \"output\",\n"
            + "        \"tags\": null\n"
            + "      },\n"
            + "      \"output_master_merchant_precision\": {\n"
            + "        \"discreteness\": \"continuous\",\n"
            + "        \"dataType\": \"fractional\",\n"
            + "        \"classifier\": \"output\",\n"
            + "        \"tags\": null\n"
            + "      }\n"
            + "    },\n"
            + "    \"metrics\": {\n"
            + "      \"weighted_f1\": {\n"
            + "        \"column\": \"weighted_f1\",\n"
            + "        \"defaultMetric\": \"median\",\n"
            + "        \"label\": \"weighted_f1\"\n"
            + "      },\n"
            + "      \"master_merchant_flag_rate\": {\n"
            + "        \"column\": \"master_merchant_flag_rate\",\n"
            + "        \"defaultMetric\": \"median\",\n"
            + "        \"label\": \"master_merchant_flag_rate\"\n"
            + "      }\n"
            + "    }\n"
            + "  },\n"
            + "  \"weightConfig\": {\n"
            + "    \"metadata\": {\n"
            + "      \"author\": \"system\",\n"
            + "      \"version\": 5,\n"
            + "      \"updatedTimestamp\": 1701817820780\n"
            + "    },\n"
            + "    \"segmentWeights\": [\n"
            + "      {\n"
            + "        \"segment\": {\n"
            + "          \"tags\": []\n"
            + "        },\n"
            + "        \"weights\": {\n"
            + "          \"activation_connected_disabled_users_through_ssn_count_by_master_merchant_from_activation_master_merchant\": 50,\n"
            + "          \"activation_connected_users_through_hard_asset_count_by_master_merchant_from_activation_master_merchant\": 30,\n"
            + "          \"business_name_fraction_uppercase_by_master_merchant_from_activation_master_merchant\": 20\n"
            + "        }\n"
            + "      }\n"
            + "    ]\n"
            + "  }\n"
            + "}";
    MonitorConfigV3JsonSerde.disableStrictParsing();

    val conf = MonitorConfigV3JsonSerde.parseMonitorConfigV3(json);
    for (val e : conf.getEntitySchema().getColumns().entrySet()) {
      if (e.getKey()
              .equals(
                  "activation_connected_users_through_hard_asset_count_by_master_merchant_from_activation_master_merchant")
          || e.getKey().equals("another_test_column")) {
        assertNull(e.getValue().getDiscreteness());
      } else {
        assertNotNull(e.getValue().getDiscreteness());
      }
    }
  }

  @Test
  public void testToastConfig() {
    MonitorConfigV3JsonSerde.disableStrictParsing();
    val conf =
        MonitorConfigV3JsonSerde.parseMonitorConfigV3(
            new ClasspathFileLoader().getFileContents("toastConfig.json"));
    assertEquals(
        DataType.INTEGRAL,
        conf.getEntitySchema()
            .getColumns()
            .get("Î©.whylabs.condition.number_of_franchise_locations.equals-1.non_matches")
            .getDataType());
  }

  @Test
  public void testWeightConfig() {
    String json =
        "{\n"
            + "  \"orgId\": \"org-hURArx\",\n"
            + "  \"metadata\": {\n"
            + "    \"author\": \"user_e284826512e5fad8892142dfa40639fb98e48b043a2b7c8735b4c99ed244e716\",\n"
            + "    \"version\": 1,\n"
            + "    \"schemaVersion\": 1,\n"
            + "    \"updatedTimestamp\": 1701750287420\n"
            + "  },\n"
            + "  \"datasetId\": \"model-72\",\n"
            + "  \"granularity\": \"daily\",\n"
            + "  \"weightConfig\": {\n"
            + "    \"defaultWeights\": {\n"
            + "      \"weights\": {\n"
            + "        \"business_name_fraction_uppercase_by_master_merchant_from_activation_master_merchant\": 20,\n"
            + "        \"activation_connected_users_through_hard_asset_count_by_master_merchant_from_activation_master_merchant\": 30,\n"
            + "        \"activation_connected_disabled_users_through_ssn_count_by_master_merchant_from_activation_master_merchant\": 50\n"
            + "      }\n"
            + "    }\n"
            + "  }\n"
            + "}";
    MonitorConfigV3JsonSerde.disableStrictParsing();

    val conf = MonitorConfigV3JsonSerde.parseMonitorConfigV3(json);
    assertEquals(conf.getWeightConfig().getDefaultWeights().getWeights().size(), 3);
  }
}
