package db

databaseChangeLog {
    include(file: 'migrations/00-initialize.sql', relativeToChangelogFile: true)
    include(file: 'migrations/01-create-audit-table.sql', relativeToChangelogFile: true)
    include(file: 'migrations/02-create-profiles-table.sql', relativeToChangelogFile: true)
    include(file: 'migrations/03-data-types.sql', relativeToChangelogFile: true)
    include(file: 'migrations/04-create-analyzer-results.sql', relativeToChangelogFile: true)
    include(file: 'migrations/05-create-backfill-table.sql', relativeToChangelogFile: true)
    include(file: 'migrations/06-create-deletion-tables.sql', relativeToChangelogFile: true)
    include(file: 'migrations/07-create-analyzer-runs.sql', relativeToChangelogFile: true)
    include(file: 'migrations/08-create-bulk-load-audit-table.sql', relativeToChangelogFile: true)
    include(file: 'migrations/09-profile-table-updates.sql', relativeToChangelogFile: true)
    include(file: 'migrations/10-audit-table-alterations.sql', relativeToChangelogFile: true)
    include(file: 'migrations/11-freq-string-operator-fields.sql', relativeToChangelogFile: true)
    include(file: 'migrations/12-ref-profile-col.sql', relativeToChangelogFile: true)
    include(file: 'migrations/13-max-io-index.sql', relativeToChangelogFile: true)
    include(file: 'migrations/14-create-tags-table.sql', relativeToChangelogFile: true)
    include(file: 'migrations/15-create-legacy-segments-table.sql', relativeToChangelogFile: true)
    include(file: 'migrations/16-index-tweaks.sql', relativeToChangelogFile: true)
    include(file: 'migrations/17-analyzer-results-partitioned.sql', relativeToChangelogFile: true)
    include(file: 'migrations/18-create-btree-gin-indices.sql', relativeToChangelogFile: true)
    include(file: 'migrations/19-btree-profile-index.sql', relativeToChangelogFile: true)
    include(file: 'migrations/20-hypertable-profiles.sql', relativeToChangelogFile: true)
    include(file: 'migrations/21-hypertable-analyzer-results.sql', relativeToChangelogFile: true)
    include(file: 'migrations/22-audit-table-updates.sql', relativeToChangelogFile: true)
    include(file: 'migrations/23-ref-profile-index.sql', relativeToChangelogFile: true)
    include(file: 'migrations/24-monitor-config.sql', relativeToChangelogFile: true)
    include(file: 'migrations/25-adhoc.sql', relativeToChangelogFile: true)
    include(file: 'migrations/26-default-tz.sql', relativeToChangelogFile: true)
    include(file: 'migrations/28-hide-segments.sql', relativeToChangelogFile: true)
    include(file: 'migrations/29-reference-profile-id.sql', relativeToChangelogFile: true)
    include(file: 'migrations/30-bulk-load-proxy-tables.sql', relativeToChangelogFile: true)
    include(file: 'migrations/31-staging-table-dead-tuple-maintenance.sql', relativeToChangelogFile: true)
    include(file: 'migrations/32-analyzer-result-constraints.sql', relativeToChangelogFile: true)
    include(file: 'migrations/33-all-profile-view.sql', relativeToChangelogFile: true)
    include(file: 'migrations/34-max-io-index.sql', relativeToChangelogFile: true)
    include(file: 'migrations/35-segmented-maxio.sql', relativeToChangelogFile: true)
    include(file: 'migrations/36-staging-max-io-fixes.sql', relativeToChangelogFile: true)
    include(file: 'migrations/37-audit-table-index.sql', relativeToChangelogFile: true)
    include(file: 'migrations/38-legacy-segments.sql', relativeToChangelogFile: true)
    include(file: 'migrations/39-analyzer-results-index.sql', relativeToChangelogFile: true)
    include(file: 'migrations/40-legacy-segment-fixes.sql', relativeToChangelogFile: true)
    include(file: 'migrations/41-ref-profile-index.sql', relativeToChangelogFile: true)
    include(file: 'migrations/42-audit_table_timestamps.sql', relativeToChangelogFile: true)
    include(file: 'migrations/43-audit_table_delete_flag.sql', relativeToChangelogFile: true)
    include(file: 'migrations/44-timeseries-table.sql', relativeToChangelogFile: true)
    include(file: 'migrations/45-analyzer-result-bulk-proxy.sql', relativeToChangelogFile: true)
    include(file: 'migrations/46-fix-segmented-table-indexing.sql', relativeToChangelogFile: true)
    include(file: 'migrations/47-segmented-maxio.sql', relativeToChangelogFile: true)
    include(file: 'migrations/48-audit-streamline.sql', relativeToChangelogFile: true)
    include(file: 'migrations/49-cache.sql', relativeToChangelogFile: true)
    include(file: 'migrations/50-analysis-indices-v2.sql', relativeToChangelogFile: true)
    include(file: 'migrations/52-maxio-cache2.sql', relativeToChangelogFile: true)
    include(file: 'migrations/54-analyzer-result-scan-fail.sql', relativeToChangelogFile: true)
    include(file: 'migrations/55-segmented-dataset-metric-selector.sql', relativeToChangelogFile: true)
    include(file: 'migrations/56-debug-event-store.sql', relativeToChangelogFile: true)
    include(file: 'migrations/57-entity-schema.sql', relativeToChangelogFile: true)
    include(file: 'migrations/58-model-type.sql', relativeToChangelogFile: true)
    include(file: 'migrations/58-org-table.sql', relativeToChangelogFile: true)
    include(file: 'migrations/59-granular-profile-table.sql', relativeToChangelogFile: true)
    include(file: 'migrations/60-model-type-enum-add.sql', relativeToChangelogFile: true)
    include(file: 'migrations/61-data-type-enum.sql', relativeToChangelogFile: true)
    include(file: 'migrations/62-ingestion-granularity-enum.sql', relativeToChangelogFile: true)
    include(file: 'migrations/63-trace-id.sql', relativeToChangelogFile: true)
    include(file: 'migrations/64-audit-table-improvements.sql', relativeToChangelogFile: true)
    include(file: 'migrations/65-debug-event-tagging.sql', relativeToChangelogFile: true)
    include(file: 'migrations/66-latest-monitor-config.sql', relativeToChangelogFile: true)
    include(file: 'migrations/67-audit-segments.sql', relativeToChangelogFile: true)
    include(file: 'migrations/68-audit-fill-factor.sql', relativeToChangelogFile: true)
    include(file: 'migrations/69-segment-trace-table.sql', relativeToChangelogFile: true)
    include(file: 'migrations/70-analyzer-result-additions-1.sql', relativeToChangelogFile: true)
    include(file: 'migrations/71-analyzer-result-additions-2.sql', relativeToChangelogFile: true)
    include(file: 'migrations/72-analyzer-result-additions-3.sql', relativeToChangelogFile: true)
    include(file: 'migrations/73-analyzer-result-bulk-loading.sql', relativeToChangelogFile: true)
    include(file: 'migrations/74-granularity-enum-values.sql', relativeToChangelogFile: true)
    include(file: 'migrations/75-adhoc-async-monitor.sql', relativeToChangelogFile: true)
    include(file: 'migrations/75-analyzer-result-bulk-fix.sql', relativeToChangelogFile: true)
    include(file: 'migrations/76-first-function.sql', relativeToChangelogFile: true)
    include(file: 'migrations/77-composite-analyzers-1.sql', relativeToChangelogFile: true)
    include(file: 'migrations/77-composite-analyzers-2.sql', relativeToChangelogFile: true)
    include(file: 'migrations/77-composite-analyzers-3.sql', relativeToChangelogFile: true)
    include(file: 'migrations/78-segment-traces-profileid.sql', relativeToChangelogFile: true)
    // Disabled until we can get query plans figured out
    //include(file: 'migrations/79-timescale-compression.sql', relativeToChangelogFile: true)
    include(file: 'migrations/79-cache-expiry.sql', relativeToChangelogFile: true)
    include(file: 'migrations/80-custom-metric-schema.sql', relativeToChangelogFile: true)
    include(file: 'migrations/81-async-adhoc-interval.sql', relativeToChangelogFile: true)
    include(file: 'migrations/82-dataset-level-table.sql', relativeToChangelogFile: true)
    include(file: 'migrations/83-custom-dashboards-table.sql', relativeToChangelogFile: true)
    include(file: 'migrations/84-custom-dashboards-alter-pk.sql', relativeToChangelogFile: true)
    include(file: 'migrations/85-custom-dashboards-index-track.sql', relativeToChangelogFile: true)
    include(file: 'migrations/86-regression-aggregate.sql', relativeToChangelogFile: true)
    include(file: 'migrations/87-classification-aggregate.sql', relativeToChangelogFile: true)
    include(file: 'migrations/88-analyzer-delete.sql', relativeToChangelogFile: true)
    include(file: 'migrations/89-tags-rollup-overhaul.sql', relativeToChangelogFile: true)
    include(file: 'migrations/90-enum-fix.sql', relativeToChangelogFile: true)
    include(file: 'migrations/91-async-feature-segment-stats.sql', relativeToChangelogFile: true)
    include(file: 'migrations/92-runid-index-async-requests.sql', relativeToChangelogFile: true)
    include(file: 'migrations/93-async-table-improvements.sql', relativeToChangelogFile: true)
    include(file: 'migrations/94-async-promotion-performance.sql', relativeToChangelogFile: true)
    include(file: 'migrations/95-adhoc-promotion-performance2.sql', relativeToChangelogFile: true)
    include(file: 'migrations/96-adhoc-promotion-performance3.sql', relativeToChangelogFile: true)
    include(file: 'migrations/97-adhoc-performance4.sql', relativeToChangelogFile: true)
    include(file: 'migrations/98-column-deletion.sql', relativeToChangelogFile: true)
    // Disabling to get timescaledb back to apache2 licence
    //include(file: 'migrations/99-dataset-statistic-retention.sql', relativeToChangelogFile: true)
    include(file: 'migrations/100-monitor-config-idx.sql', relativeToChangelogFile: true)
    include(file: 'migrations/101-feature-weights.sql', relativeToChangelogFile: true)
    include(file: 'migrations/102-dataset-statistics-extended.sql', relativeToChangelogFile: true)
    // Disabling to get timescaledb back to apache2 licence
    //include(file: 'migrations/103-dataset-statistics-extended2.sql', relativeToChangelogFile: true)
    include(file: 'migrations/102-dataset-table.sql', relativeToChangelogFile: true)
    include(file: 'migrations/104-reingest.sql', relativeToChangelogFile: true)

    /**
     * Important note: We're launching the pg_cron backed flow separately. That needs to be stable enough that we
     * know we don't wanna roll back before we commit to flipping this on. See liquibase-changelog and uncomment when
     * ready
     */
    //include(file: 'migrations/106-add-compression.sql', relativeToChangelogFile: true)

    // Disabling to get timescaledb back to apache2 licence
    //include(file: 'migrations/105-diff-bounds.sql', relativeToChangelogFile: true)
    include(file: 'migrations/106-diff-bounds-rollback.sql', relativeToChangelogFile: true)
    include(file: 'migrations/107-reorder-policy.sql', relativeToChangelogFile: true)

    include(file: 'migrations/109-pg-cron-1.sql', relativeToChangelogFile: true)
    include(file: 'migrations/109-pg-cron-2.sql', relativeToChangelogFile: true)
    include(file: 'migrations/109-pg-cron-3.sql', relativeToChangelogFile: true)

    // This one is too slow for liquibase and only blocks 106-add-compression.sql which isn't enabled yet
    //include(file: 'migrations/109-pg-cron-4.sql', relativeToChangelogFile: true)
    include(file: 'migrations/109-pg-cron-5.sql', relativeToChangelogFile: true)
    include(file: 'migrations/109-pg-cron-6.sql', relativeToChangelogFile: true)

    // Baking in prod for a while before committing
    //  include(file: 'migrations/108-dataset-stat-policy.sql', relativeToChangelogFile: true)

    // Disabling to get timescaledb back to apache2 licence
    //include(file: 'migrations/110-retention.sql', relativeToChangelogFile: true)
    include(file: 'migrations/111-faster-analyzer-result-ingest.sql', relativeToChangelogFile: true)
    include(file: 'migrations/112-rollback-views.sql', relativeToChangelogFile: true)

    // Disabling to get timescaledb back to apache2 licence
    //include(file: 'migrations/113-adjust-retention.sql', relativeToChangelogFile: true)
    include(file: 'migrations/114-scheduler.sql', relativeToChangelogFile: true)
    include(file: 'migrations/115-ref-profile-indicies.sql', relativeToChangelogFile: true)
    include(file: 'migrations/116-scheduler-phase-2.sql', relativeToChangelogFile: true)
    include(file: 'migrations/117-scheduler-phase3.sql', relativeToChangelogFile: true)
    include(file: 'migrations/118-scheduler-late-data-queue.sql', relativeToChangelogFile: true)

    include(file: 'migrations/114-customer-events.sql', relativeToChangelogFile: true)
    include(file: 'migrations/119-notifications-tables.sql', relativeToChangelogFile: true)
    include(file: 'migrations/120-failure-types.sql', relativeToChangelogFile: true)
    include(file: 'migrations/121-anomaly-count-index.sql', relativeToChangelogFile: true)
    include(file: 'migrations/122-dataset-table-add-cols.sql', relativeToChangelogFile: true)
    include(file: 'migrations/123-failure-type.sql', relativeToChangelogFile: true)
    include(file: 'migrations/124-repl-lag.sql', relativeToChangelogFile: true)
    include(file: 'migrations/126-feature-stats.sql', relativeToChangelogFile: true)
    include(file: 'migrations/128-partial-target-batch.sql', relativeToChangelogFile: true)
    include(file: 'migrations/129-personal-queues.sql', relativeToChangelogFile: true)
    include(file: 'migrations/130-retention-contention.sql', relativeToChangelogFile: true)
    include(file: 'migrations/131-create-resource-tags-table.sql', relativeToChangelogFile: true)
    include(file: 'migrations/132-analyzer-runs.sql', relativeToChangelogFile: true)
    include(file: 'migrations/133-analyzer-run-view.sql', relativeToChangelogFile: true)
    include(file: 'migrations/134-monitor-config-latest.sql', relativeToChangelogFile: true)
    include(file: 'migrations/135-disabled-schedule.sql', relativeToChangelogFile: true)
    include(file: 'migrations/136-stuck-requests.sql', relativeToChangelogFile: true)
    include(file: 'migrations/137-retention.sql', relativeToChangelogFile: true)
    include(file: 'migrations/138-typo.sql', relativeToChangelogFile: true)
    include(file: 'migrations/139-demo-data-looper.sql', relativeToChangelogFile: true)
    include(file: 'migrations/139-org-resource-tags.sql', relativeToChangelogFile: true)
    include(file: 'migrations/140-update-resource-tags-unique-constrain.sql', relativeToChangelogFile: true)
    include(file: 'migrations/141-frequent-string-samples.sql', relativeToChangelogFile: true)
    include(file: 'migrations/142-staging-table-min-max.sql', relativeToChangelogFile: true)


}
