{{- if .Values.service.create }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name | default .Release.Name }}
  labels:
    {{- include "dataservice.labels" . | nindent 4 }}
  {{- if .Values.service.annotations }}
  annotations:
    {{- .Values.service.annotations | toYaml | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  selector:
    {{- include "dataservice.selectorLabels" . | nindent 4 }}
{{- end }}