package ai.whylabs.dataservice.diagnostics.enums;

public enum GeneralObservation {
  ANALYZER_REMOVED_AFTER_ANALYSIS,
  ANALYZER_CONFIGURATION_UPDATED_AFTER_ANALYSIS,
  BASELINE_LATE_DATA,
  TARGET_LATE_DATA,
  SCHEMA_CHANGE,
  DISCRETENESS_CHANGE,
  SEGMENTS_CHANGE
}
